*/ 100 - No name specified
*
*\

\* Warps */

(0:1) Whenever someone moves,
 (1:35) and they move into position (10, 6),
    (5:19) move the triggering player to (39, 43, 16).

(0:1) Whenever someone moves,
 (1:35) and they move into position (10, 7),
    (5:19) move the triggering player to (39, 43, 16).

\* NPC Spawns */
(0:0) When everything is starting up,
    (5:220) spawn a new NPC 43 at (1, 8) on the map.

