*/ 129 - No name specified
*
*\

\* Warps */

(0:1) Whenever someone moves,
 (1:35) and they move into position (42, 0),
    (5:19) move the triggering player to (1, 59, 130).

(0:1) Whenever someone moves,
 (1:35) and they move into position (43, 0),
    (5:19) move the triggering player to (2, 59, 130).

(0:1) Whenever someone moves,
 (1:35) and they move into position (44, 0),
    (5:19) move the triggering player to (3, 59, 130).

(0:1) Whenever someone moves,
 (1:35) and they move into position (45, 0),
    (5:19) move the triggering player to (4, 59, 130).

(0:1) Whenever someone moves,
 (1:35) and they move into position (9, 1),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (17, 1),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (19, 1),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (25, 1),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (32, 1),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (36, 1),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (42, 1),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (47, 1),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (6, 2),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (8, 2),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (11, 2),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 2),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (15, 2),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (20, 2),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (22, 2),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (26, 2),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (28, 2),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (30, 2),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (33, 2),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (35, 2),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (37, 2),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (40, 2),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (43, 2),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (45, 2),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (5, 3),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (9, 3),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 3),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (14, 3),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (16, 3),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (21, 3),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (24, 3),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (27, 3),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (30, 3),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (32, 3),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (39, 3),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (44, 3),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (46, 3),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (7, 4),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (11, 4),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (17, 4),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (19, 4),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (23, 4),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (29, 4),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (35, 4),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (37, 4),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (40, 4),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (42, 4),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (48, 4),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (50, 4),
    (5:19) move the triggering player to (4, 4, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (1, 10),
    (5:19) move the triggering player to (4, 1, 128).

(0:1) Whenever someone moves,
 (1:35) and they move into position (2, 10),
    (5:19) move the triggering player to (5, 1, 128).

(0:1) Whenever someone moves,
 (1:35) and they move into position (3, 10),
    (5:19) move the triggering player to (6, 1, 128).

(0:1) Whenever someone moves,
 (1:35) and they move into position (4, 10),
    (5:19) move the triggering player to (7, 1, 128).

\* NPC Spawns */
(0:0) When everything is starting up,
    (5:220) spawn a new NPC 81 at (3, 3) on the map.
    (5:220) spawn a new NPC 81 at (12, 3) on the map.
    (5:220) spawn a new NPC 81 at (21, 3) on the map.
    (5:220) spawn a new NPC 81 at (30, 3) on the map.
    (5:220) spawn a new NPC 81 at (39, 3) on the map.

