*/ 132 - No name specified
*
*\

\* Warps */

(0:1) Whenever someone moves,
 (1:35) and they move into position (8, 2),
    (5:19) move the triggering player to (24, 54, 130).

(0:1) Whenever someone moves,
 (1:35) and they move into position (7, 7),
    (5:19) move the triggering player to (25, 7, 130).

(0:1) Whenever someone moves,
 (1:35) and they move into position (1, 9),
    (5:19) move the triggering player to (15, 33, 130).

\* NPC Spawns */
(0:0) When everything is starting up,

