*/ 135 - No name specified
*
*\

\* Warps */

(0:1) Whenever someone moves,
 (1:35) and they move into position (7, 0),
    (5:19) move the triggering player to (3, 27, 144).

(0:1) Whenever someone moves,
 (1:35) and they move into position (7, 1),
    (5:19) move the triggering player to (3, 27, 144).

\* NPC Spawns */
(0:0) When everything is starting up,
    (5:220) spawn a new NPC 91 at (5, 5) on the map.
    (5:220) spawn a new NPC 92 at (5, 5) on the map.

