*/ 136 - Hall of Pain
*
*\

\* Warps */

(0:1) Whenever someone moves,
 (1:35) and they move into position (2, 0),
    (5:19) move the triggering player to (18, 3, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (3, 0),
    (5:19) move the triggering player to (7, 19, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (48, 0),
    (5:19) move the triggering player to (22, 21, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (18, 1),
    (5:19) move the triggering player to (22, 21, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (83, 4),
    (5:19) move the triggering player to (88, 77, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (5, 18),
    (5:19) move the triggering player to (3, 2, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (83, 18),
    (5:19) move the triggering player to (88, 36, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (5, 19),
    (5:19) move the triggering player to (3, 45, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (23, 21),
    (5:19) move the triggering player to (48, 2, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (83, 34),
    (5:19) move the triggering player to (83, 20, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (88, 34),
    (5:19) move the triggering player to (46, 68, 249).

(0:1) Whenever someone moves,
 (1:35) and they move into position (2, 41),
    (5:19) move the triggering player to (3, 88, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (4, 41),
    (5:19) move the triggering player to (3, 88, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (9, 41),
    (5:19) move the triggering player to (7, 19, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (11, 41),
    (5:19) move the triggering player to (20, 13, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 43),
    (5:19) move the triggering player to (3, 88, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 45),
    (5:19) move the triggering player to (3, 88, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (7, 46),
    (5:19) move the triggering player to (7, 84, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 47),
    (5:19) move the triggering player to (7, 19, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 49),
    (5:19) move the triggering player to (3, 88, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 51),
    (5:19) move the triggering player to (20, 13, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 53),
    (5:19) move the triggering player to (3, 88, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 55),
    (5:19) move the triggering player to (3, 88, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (89, 55),
    (5:19) move the triggering player to (82, 82, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 57),
    (5:19) move the triggering player to (20, 13, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 66),
    (5:19) move the triggering player to (21, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (56, 76),
    (5:19) move the triggering player to (3, 88, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (80, 79),
    (5:19) move the triggering player to (88, 36, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (80, 82),
    (5:19) move the triggering player to (89, 56, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (80, 85),
    (5:19) move the triggering player to (88, 36, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (1, 86),
    (5:19) move the triggering player to (26, 88, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (1, 88),
    (5:19) move the triggering player to (56, 78, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (24, 88),
    (5:19) move the triggering player to (3, 86, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (80, 88),
    (5:19) move the triggering player to (88, 36, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (4, 103),
    (5:19) move the triggering player to (2, 119, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (8, 103),
    (5:19) move the triggering player to (2, 66, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 103),
    (5:19) move the triggering player to (33, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (16, 103),
    (5:19) move the triggering player to (33, 129, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (21, 103),
    (5:19) move the triggering player to (2, 66, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (28, 103),
    (5:19) move the triggering player to (2, 119, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (52, 103),
    (5:19) move the triggering player to (8, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (10, 104),
    (5:19) move the triggering player to (2, 115, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (19, 104),
    (5:19) move the triggering player to (2, 115, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (27, 104),
    (5:19) move the triggering player to (21, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (31, 104),
    (5:19) move the triggering player to (21, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 105),
    (5:19) move the triggering player to (22, 114, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (3, 105),
    (5:19) move the triggering player to (2, 115, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 105),
    (5:19) move the triggering player to (31, 128, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (16, 105),
    (5:19) move the triggering player to (31, 128, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (19, 105),
    (5:19) move the triggering player to (2, 115, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (31, 105),
    (5:19) move the triggering player to (21, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (3, 106),
    (5:19) move the triggering player to (2, 115, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (11, 106),
    (5:19) move the triggering player to (31, 128, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (16, 106),
    (5:19) move the triggering player to (13, 131, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (25, 106),
    (5:19) move the triggering player to (13, 131, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (27, 106),
    (5:19) move the triggering player to (13, 131, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (28, 106),
    (5:19) move the triggering player to (13, 131, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (31, 106),
    (5:19) move the triggering player to (13, 131, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (5, 107),
    (5:19) move the triggering player to (31, 128, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (10, 107),
    (5:19) move the triggering player to (31, 128, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (22, 107),
    (5:19) move the triggering player to (13, 131, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (25, 107),
    (5:19) move the triggering player to (13, 131, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (1, 108),
    (5:19) move the triggering player to (2, 115, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (5, 108),
    (5:19) move the triggering player to (31, 128, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 108),
    (5:19) move the triggering player to (31, 128, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (14, 108),
    (5:19) move the triggering player to (16, 139, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (16, 108),
    (5:19) move the triggering player to (31, 128, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (18, 108),
    (5:19) move the triggering player to (13, 131, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (22, 108),
    (5:19) move the triggering player to (28, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (27, 108),
    (5:19) move the triggering player to (16, 139, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (28, 108),
    (5:19) move the triggering player to (2, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (30, 108),
    (5:19) move the triggering player to (13, 131, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (46, 108),
    (5:19) move the triggering player to (72, 126, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 109),
    (5:19) move the triggering player to (2, 119, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (2, 109),
    (5:19) move the triggering player to (2, 115, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (4, 109),
    (5:19) move the triggering player to (31, 128, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (8, 109),
    (5:19) move the triggering player to (31, 128, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (16, 109),
    (5:19) move the triggering player to (31, 128, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (17, 109),
    (5:19) move the triggering player to (31, 128, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (18, 109),
    (5:19) move the triggering player to (13, 131, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (31, 109),
    (5:19) move the triggering player to (13, 131, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (5, 110),
    (5:19) move the triggering player to (31, 128, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (14, 110),
    (5:19) move the triggering player to (2, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (18, 110),
    (5:19) move the triggering player to (13, 131, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (19, 110),
    (5:19) move the triggering player to (31, 128, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (23, 110),
    (5:19) move the triggering player to (13, 131, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (27, 110),
    (5:19) move the triggering player to (2, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (29, 110),
    (5:19) move the triggering player to (5, 119, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (46, 110),
    (5:19) move the triggering player to (72, 126, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (70, 110),
    (5:19) move the triggering player to (48, 114, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (4, 111),
    (5:19) move the triggering player to (31, 128, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (6, 111),
    (5:19) move the triggering player to (31, 128, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (10, 111),
    (5:19) move the triggering player to (31, 128, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (14, 111),
    (5:19) move the triggering player to (2, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (27, 111),
    (5:19) move the triggering player to (2, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (29, 111),
    (5:19) move the triggering player to (2, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (6, 112),
    (5:19) move the triggering player to (2, 66, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 112),
    (5:19) move the triggering player to (2, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (17, 112),
    (5:19) move the triggering player to (31, 128, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (24, 112),
    (5:19) move the triggering player to (13, 131, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (29, 112),
    (5:19) move the triggering player to (2, 66, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (46, 112),
    (5:19) move the triggering player to (20, 12, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (6, 113),
    (5:19) move the triggering player to (31, 128, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (7, 113),
    (5:19) move the triggering player to (31, 128, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (14, 113),
    (5:19) move the triggering player to (20, 139, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (15, 113),
    (5:19) move the triggering player to (33, 121, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (16, 113),
    (5:19) move the triggering player to (28, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (26, 113),
    (5:19) move the triggering player to (2, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (27, 113),
    (5:19) move the triggering player to (16, 139, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (28, 113),
    (5:19) move the triggering player to (2, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (29, 113),
    (5:19) move the triggering player to (16, 139, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (1, 114),
    (5:19) move the triggering player to (21, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (3, 114),
    (5:19) move the triggering player to (21, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (8, 114),
    (5:19) move the triggering player to (24, 126, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (9, 114),
    (5:19) move the triggering player to (24, 126, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 114),
    (5:19) move the triggering player to (31, 128, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (14, 114),
    (5:19) move the triggering player to (33, 121, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (15, 114),
    (5:19) move the triggering player to (33, 121, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (16, 114),
    (5:19) move the triggering player to (28, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (46, 114),
    (5:19) move the triggering player to (72, 126, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 115),
    (5:19) move the triggering player to (2, 66, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (4, 115),
    (5:19) move the triggering player to (21, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (14, 115),
    (5:19) move the triggering player to (33, 121, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (18, 115),
    (5:19) move the triggering player to (13, 131, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (20, 115),
    (5:19) move the triggering player to (33, 121, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (31, 115),
    (5:19) move the triggering player to (13, 131, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (6, 116),
    (5:19) move the triggering player to (14, 123, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (7, 116),
    (5:19) move the triggering player to (14, 123, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 116),
    (5:19) move the triggering player to (5, 121, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (15, 116),
    (5:19) move the triggering player to (13, 131, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (17, 116),
    (5:19) move the triggering player to (33, 121, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (21, 116),
    (5:19) move the triggering player to (33, 121, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (29, 116),
    (5:19) move the triggering player to (5, 119, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (46, 116),
    (5:19) move the triggering player to (20, 12, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (1, 117),
    (5:19) move the triggering player to (21, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (2, 117),
    (5:19) move the triggering player to (21, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (3, 117),
    (5:19) move the triggering player to (21, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (6, 117),
    (5:19) move the triggering player to (14, 123, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (21, 117),
    (5:19) move the triggering player to (33, 121, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (25, 117),
    (5:19) move the triggering player to (5, 121, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (26, 117),
    (5:19) move the triggering player to (13, 131, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (27, 117),
    (5:19) move the triggering player to (13, 131, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (29, 117),
    (5:19) move the triggering player to (5, 119, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (30, 117),
    (5:19) move the triggering player to (7, 123, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (31, 117),
    (5:19) move the triggering player to (13, 131, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (5, 118),
    (5:19) move the triggering player to (14, 123, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (10, 118),
    (5:19) move the triggering player to (31, 128, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 118),
    (5:19) move the triggering player to (31, 128, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (14, 118),
    (5:19) move the triggering player to (7, 123, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (17, 118),
    (5:19) move the triggering player to (7, 123, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (18, 118),
    (5:19) move the triggering player to (7, 123, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (30, 118),
    (5:19) move the triggering player to (5, 119, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 119),
    (5:19) move the triggering player to (2, 119, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (5, 119),
    (5:19) move the triggering player to (14, 123, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (14, 119),
    (5:19) move the triggering player to (7, 123, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (17, 119),
    (5:19) move the triggering player to (3, 126, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (20, 119),
    (5:19) move the triggering player to (33, 121, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (24, 119),
    (5:19) move the triggering player to (5, 121, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (29, 119),
    (5:19) move the triggering player to (7, 123, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (5, 120),
    (5:19) move the triggering player to (14, 123, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (8, 120),
    (5:19) move the triggering player to (14, 123, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (10, 120),
    (5:19) move the triggering player to (31, 128, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 120),
    (5:19) move the triggering player to (31, 128, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (16, 120),
    (5:19) move the triggering player to (3, 126, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (26, 120),
    (5:19) move the triggering player to (3, 121, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (2, 121),
    (5:19) move the triggering player to (31, 128, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (3, 121),
    (5:19) move the triggering player to (31, 128, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (5, 121),
    (5:19) move the triggering player to (14, 123, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 121),
    (5:19) move the triggering player to (31, 128, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (17, 121),
    (5:19) move the triggering player to (7, 123, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (20, 121),
    (5:19) move the triggering player to (2, 132, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (26, 121),
    (5:19) move the triggering player to (3, 121, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (28, 121),
    (5:19) move the triggering player to (7, 123, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (31, 121),
    (5:19) move the triggering player to (7, 123, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (3, 122),
    (5:19) move the triggering player to (31, 128, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (20, 122),
    (5:19) move the triggering player to (2, 132, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (23, 122),
    (5:19) move the triggering player to (16, 139, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (24, 122),
    (5:19) move the triggering player to (16, 139, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (28, 122),
    (5:19) move the triggering player to (7, 123, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (4, 123),
    (5:19) move the triggering player to (31, 128, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (8, 123),
    (5:19) move the triggering player to (24, 106, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 123),
    (5:19) move the triggering player to (14, 123, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (15, 123),
    (5:19) move the triggering player to (14, 123, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (16, 123),
    (5:19) move the triggering player to (2, 66, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (17, 123),
    (5:19) move the triggering player to (14, 123, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (20, 123),
    (5:19) move the triggering player to (28, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (21, 123),
    (5:19) move the triggering player to (7, 123, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (8, 124),
    (5:19) move the triggering player to (24, 106, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (9, 124),
    (5:19) move the triggering player to (20, 139, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 124),
    (5:19) move the triggering player to (14, 123, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (20, 124),
    (5:19) move the triggering player to (3, 121, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (28, 124),
    (5:19) move the triggering player to (5, 119, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (8, 125),
    (5:19) move the triggering player to (24, 106, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 125),
    (5:19) move the triggering player to (14, 123, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (14, 125),
    (5:19) move the triggering player to (31, 128, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (17, 125),
    (5:19) move the triggering player to (2, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (19, 125),
    (5:19) move the triggering player to (3, 121, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (22, 125),
    (5:19) move the triggering player to (2, 132, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (23, 125),
    (5:19) move the triggering player to (25, 110, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (24, 125),
    (5:19) move the triggering player to (16, 139, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (28, 125),
    (5:19) move the triggering player to (5, 119, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 126),
    (5:19) move the triggering player to (2, 132, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 126),
    (5:19) move the triggering player to (14, 123, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (15, 126),
    (5:19) move the triggering player to (31, 128, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (17, 126),
    (5:19) move the triggering player to (20, 139, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (19, 126),
    (5:19) move the triggering player to (3, 121, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (21, 126),
    (5:19) move the triggering player to (2, 132, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (25, 126),
    (5:19) move the triggering player to (2, 132, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (29, 126),
    (5:19) move the triggering player to (7, 123, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (72, 126),
    (5:19) move the triggering player to (52, 115, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (82, 126),
    (5:19) move the triggering player to (72, 137, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (88, 126),
    (5:19) move the triggering player to (72, 110, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (1, 127),
    (5:19) move the triggering player to (2, 115, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (3, 127),
    (5:19) move the triggering player to (2, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (4, 127),
    (5:19) move the triggering player to (2, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (5, 127),
    (5:19) move the triggering player to (20, 139, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (6, 127),
    (5:19) move the triggering player to (28, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (9, 127),
    (5:19) move the triggering player to (28, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (17, 127),
    (5:19) move the triggering player to (20, 139, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (21, 127),
    (5:19) move the triggering player to (16, 139, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (23, 127),
    (5:19) move the triggering player to (2, 132, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (24, 127),
    (5:19) move the triggering player to (52, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (26, 127),
    (5:19) move the triggering player to (2, 132, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (2, 128),
    (5:19) move the triggering player to (2, 115, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (10, 128),
    (5:19) move the triggering player to (31, 128, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 128),
    (5:19) move the triggering player to (16, 106, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (17, 128),
    (5:19) move the triggering player to (2, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (20, 128),
    (5:19) move the triggering player to (25, 110, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (24, 128),
    (5:19) move the triggering player to (25, 110, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (25, 128),
    (5:19) move the triggering player to (2, 132, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (78, 128),
    (5:19) move the triggering player to (85, 133, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 129),
    (5:19) move the triggering player to (33, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (14, 129),
    (5:19) move the triggering player to (16, 106, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (15, 129),
    (5:19) move the triggering player to (2, 132, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (21, 129),
    (5:19) move the triggering player to (2, 132, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (24, 129),
    (5:19) move the triggering player to (2, 132, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (28, 129),
    (5:19) move the triggering player to (5, 119, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (29, 129),
    (5:19) move the triggering player to (5, 119, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (30, 129),
    (5:19) move the triggering player to (2, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (32, 129),
    (5:19) move the triggering player to (2, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (33, 129),
    (5:19) move the triggering player to (2, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (3, 130),
    (5:19) move the triggering player to (2, 132, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (7, 130),
    (5:19) move the triggering player to (31, 128, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (9, 130),
    (5:19) move the triggering player to (14, 123, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (10, 130),
    (5:19) move the triggering player to (14, 123, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (15, 130),
    (5:19) move the triggering player to (16, 106, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (16, 130),
    (5:19) move the triggering player to (16, 106, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (23, 130),
    (5:19) move the triggering player to (2, 132, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (28, 130),
    (5:19) move the triggering player to (5, 119, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (87, 130),
    (5:19) move the triggering player to (72, 137, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (89, 130),
    (5:19) move the triggering player to (72, 137, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (1, 131),
    (5:19) move the triggering player to (2, 115, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (2, 131),
    (5:19) move the triggering player to (2, 115, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (8, 131),
    (5:19) move the triggering player to (16, 106, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (9, 131),
    (5:19) move the triggering player to (28, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 131),
    (5:19) move the triggering player to (31, 128, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (21, 131),
    (5:19) move the triggering player to (20, 139, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (29, 131),
    (5:19) move the triggering player to (2, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (30, 131),
    (5:19) move the triggering player to (2, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (31, 131),
    (5:19) move the triggering player to (2, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (32, 131),
    (5:19) move the triggering player to (2, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (72, 131),
    (5:19) move the triggering player to (72, 137, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (77, 131),
    (5:19) move the triggering player to (85, 133, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 132),
    (5:19) move the triggering player to (28, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (2, 132),
    (5:19) move the triggering player to (2, 115, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (5, 132),
    (5:19) move the triggering player to (28, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (7, 132),
    (5:19) move the triggering player to (31, 128, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (9, 132),
    (5:19) move the triggering player to (28, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (16, 132),
    (5:19) move the triggering player to (16, 139, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (21, 132),
    (5:19) move the triggering player to (2, 132, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (22, 132),
    (5:19) move the triggering player to (25, 110, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (75, 132),
    (5:19) move the triggering player to (85, 133, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (5, 133),
    (5:19) move the triggering player to (14, 123, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (9, 133),
    (5:19) move the triggering player to (16, 106, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 133),
    (5:19) move the triggering player to (14, 123, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (18, 133),
    (5:19) move the triggering player to (16, 139, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (72, 133),
    (5:19) move the triggering player to (75, 137, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (77, 133),
    (5:19) move the triggering player to (83, 136, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (79, 133),
    (5:19) move the triggering player to (85, 133, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (85, 133),
    (5:19) move the triggering player to (48, 108, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (5, 134),
    (5:19) move the triggering player to (14, 123, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (6, 134),
    (5:19) move the triggering player to (14, 123, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (9, 134),
    (5:19) move the triggering player to (16, 106, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 134),
    (5:19) move the triggering player to (20, 139, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (20, 134),
    (5:19) move the triggering player to (16, 139, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (21, 134),
    (5:19) move the triggering player to (16, 139, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (24, 134),
    (5:19) move the triggering player to (16, 139, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (26, 134),
    (5:19) move the triggering player to (16, 139, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 135),
    (5:19) move the triggering player to (28, 105, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 136),
    (5:19) move the triggering player to (14, 123, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (17, 136),
    (5:19) move the triggering player to (2, 115, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (21, 136),
    (5:19) move the triggering player to (2, 115, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (32, 136),
    (5:19) move the triggering player to (2, 115, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (77, 136),
    (5:19) move the triggering player to (78, 128, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (83, 136),
    (5:19) move the triggering player to (85, 133, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (72, 137),
    (5:19) move the triggering player to (52, 115, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (75, 137),
    (5:19) move the triggering player to (52, 115, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (88, 137),
    (5:19) move the triggering player to (82, 126, 136).

(0:1) Whenever someone moves,
 (1:35) and they move into position (77, 138),
    (5:19) move the triggering player to (72, 137, 136).

\* NPC Spawns */
(0:0) When everything is starting up,
    (5:220) spawn a new NPC 171 at (80, 13) on the map.
    (5:220) spawn a new NPC 171 at (88, 13) on the map.
    (5:220) spawn a new NPC 171 at (80, 8) on the map.
    (5:220) spawn a new NPC 171 at (88, 8) on the map.
    (5:220) spawn a new NPC 171 at (84, 7) on the map.
    (5:220) spawn a new NPC 9 at (84, 11) on the map.
    (5:220) spawn a new NPC 171 at (85, 85) on the map.
    (5:220) spawn a new NPC 2 at (30, 75) on the map.
    (5:220) spawn a new NPC 2 at (30, 80) on the map.
    (5:220) spawn a new NPC 2 at (30, 85) on the map.
    (5:220) spawn a new NPC 227 at (54, 87) on the map.
    (5:220) spawn a new NPC 227 at (54, 80) on the map.
    (5:220) spawn a new NPC 227 at (60, 87) on the map.
    (5:220) spawn a new NPC 227 at (60, 80) on the map.
    (5:220) spawn a new NPC 239 at (56, 83) on the map.
    (5:220) spawn a new NPC 171 at (7, 66) on the map.
    (5:220) spawn a new NPC 227 at (13, 6) on the map.
    (5:220) spawn a new NPC 257 at (49, 15) on the map.
    (5:220) spawn a new NPC 256 at (41, 15) on the map.
    (5:220) spawn a new NPC 256 at (41, 8) on the map.
    (5:220) spawn a new NPC 256 at (41, 21) on the map.
    (5:220) spawn a new NPC 256 at (48, 8) on the map.
    (5:220) spawn a new NPC 256 at (48, 21) on the map.
    (5:220) spawn a new NPC 256 at (54, 8) on the map.
    (5:220) spawn a new NPC 256 at (54, 15) on the map.
    (5:220) spawn a new NPC 256 at (54, 21) on the map.
    (5:220) spawn a new NPC 194 at (9, 119) on the map.
    (5:220) spawn a new NPC 194 at (12, 132) on the map.
    (5:220) spawn a new NPC 194 at (31, 112) on the map.
    (5:220) spawn a new NPC 194 at (30, 127) on the map.
    (5:220) spawn a new NPC 129 at (80, 110) on the map.
    (5:220) spawn a new NPC 129 at (76, 105) on the map.

