*/ 15 - Aeven Church
*
*\

\* Warps */

(0:1) Whenever someone moves,
 (1:35) and they move into position (18, 8),
    (5:19) move the triggering player to (37, 35, 5).

(0:1) Whenever someone moves,
 (1:35) and they move into position (18, 9),
    (5:19) move the triggering player to (37, 35, 5).

\* NPC Spawns */
(0:0) When everything is starting up,
    (5:220) spawn a new NPC 114 at (6, 8) on the map.

