*/ 157 - No name specified
*
*\

\* Warps */

(0:1) Whenever someone moves,
 (1:35) and they move into position (4, 14),
    (5:19) move the triggering player to (18, 59, 5).

(0:1) Whenever someone moves,
 (1:35) and they move into position (5, 14),
    (5:19) move the triggering player to (18, 59, 5).

\* NPC Spawns */
(0:0) When everything is starting up,
    (5:220) spawn a new NPC 115 at (5, 2) on the map.

