*/ 160 - No name specified
*
*\

\* Warps */

(0:1) Whenever someone moves,
 (1:35) and they move into position (3, 0),
    (5:19) move the triggering player to (1, 14, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (4, 0),
    (5:19) move the triggering player to (1, 14, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (5, 0),
    (5:19) move the triggering player to (1, 14, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (16, 0),
    (5:19) move the triggering player to (22, 47, 161).

(0:1) Whenever someone moves,
 (1:35) and they move into position (17, 0),
    (5:19) move the triggering player to (23, 47, 161).

(0:1) Whenever someone moves,
 (1:35) and they move into position (18, 0),
    (5:19) move the triggering player to (24, 47, 161).

(0:1) Whenever someone moves,
 (1:35) and they move into position (19, 0),
    (5:19) move the triggering player to (25, 47, 161).

(0:1) Whenever someone moves,
 (1:35) and they move into position (31, 0),
    (5:19) move the triggering player to (59, 62, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (32, 0),
    (5:19) move the triggering player to (59, 62, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (33, 0),
    (5:19) move the triggering player to (59, 62, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (34, 0),
    (5:19) move the triggering player to (59, 62, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (54, 0),
    (5:19) move the triggering player to (16, 63, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (55, 0),
    (5:19) move the triggering player to (16, 63, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (56, 0),
    (5:19) move the triggering player to (16, 63, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (11, 1),
    (5:19) move the triggering player to (51, 8, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (14, 1),
    (5:19) move the triggering player to (16, 9, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (36, 2),
    (5:19) move the triggering player to (16, 63, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (15, 8),
    (5:19) move the triggering player to (4, 1, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (51, 8),
    (5:19) move the triggering player to (11, 1, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (14, 9),
    (5:19) move the triggering player to (56, 9, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (16, 9),
    (5:19) move the triggering player to (14, 1, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (56, 9),
    (5:19) move the triggering player to (14, 9, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (56, 10),
    (5:19) move the triggering player to (44, 61, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (57, 10),
    (5:19) move the triggering player to (51, 8, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 12),
    (5:19) move the triggering player to (4, 1, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 13),
    (5:19) move the triggering player to (4, 1, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 14),
    (5:19) move the triggering player to (4, 1, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 15),
    (5:19) move the triggering player to (4, 1, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (64, 15),
    (5:19) move the triggering player to (59, 63, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (64, 16),
    (5:19) move the triggering player to (59, 63, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (64, 17),
    (5:19) move the triggering player to (59, 63, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (56, 19),
    (5:19) move the triggering player to (46, 60, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (16, 29),
    (5:19) move the triggering player to (1, 49, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 33),
    (5:19) move the triggering player to (16, 63, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 34),
    (5:19) move the triggering player to (16, 63, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (64, 34),
    (5:19) move the triggering player to (16, 63, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 35),
    (5:19) move the triggering player to (16, 63, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (64, 35),
    (5:19) move the triggering player to (16, 63, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 36),
    (5:19) move the triggering player to (16, 63, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (64, 36),
    (5:19) move the triggering player to (16, 63, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (19, 38),
    (5:19) move the triggering player to (23, 62, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (31, 38),
    (5:19) move the triggering player to (62, 44, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 39),
    (5:19) move the triggering player to (16, 63, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 40),
    (5:19) move the triggering player to (16, 63, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (62, 44),
    (5:19) move the triggering player to (31, 38, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 48),
    (5:19) move the triggering player to (37, 63, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (1, 49),
    (5:19) move the triggering player to (16, 29, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (46, 60),
    (5:19) move the triggering player to (56, 19, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (37, 61),
    (5:19) move the triggering player to (16, 63, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (44, 61),
    (5:19) move the triggering player to (56, 10, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (23, 62),
    (5:19) move the triggering player to (16, 63, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (37, 63),
    (5:19) move the triggering player to (0, 48, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (15, 64),
    (5:19) move the triggering player to (22, 1, 159).

(0:1) Whenever someone moves,
 (1:35) and they move into position (16, 64),
    (5:19) move the triggering player to (23, 1, 159).

(0:1) Whenever someone moves,
 (1:35) and they move into position (17, 64),
    (5:19) move the triggering player to (24, 1, 159).

(0:1) Whenever someone moves,
 (1:35) and they move into position (57, 64),
    (5:19) move the triggering player to (63, 15, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (58, 64),
    (5:19) move the triggering player to (63, 15, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (59, 64),
    (5:19) move the triggering player to (63, 15, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (60, 64),
    (5:19) move the triggering player to (63, 15, 160).

(0:1) Whenever someone moves,
 (1:35) and they move into position (61, 64),
    (5:19) move the triggering player to (63, 15, 160).

\* NPC Spawns */
(0:0) When everything is starting up,
    (5:220) spawn a new NPC 121 at (7, 33) on the map.
    (5:220) spawn a new NPC 121 at (22, 35) on the map.
    (5:220) spawn a new NPC 121 at (36, 35) on the map.
    (5:220) spawn a new NPC 121 at (53, 39) on the map.
    (5:220) spawn a new NPC 121 at (59, 59) on the map.
    (5:220) spawn a new NPC 121 at (59, 14) on the map.
    (5:220) spawn a new NPC 121 at (37, 12) on the map.
    (5:220) spawn a new NPC 121 at (30, 21) on the map.
    (5:220) spawn a new NPC 121 at (3, 17) on the map.
    (5:220) spawn a new NPC 121 at (3, 17) on the map.

