*/ 167 - Joseh's house
*
*\

\* Warps */

(0:1) Whenever someone moves,
 (1:35) and they move into position (4, 10),
    (5:19) move the triggering player to (4, 60, 166).

(0:1) Whenever someone moves,
 (1:35) and they move into position (5, 10),
    (5:19) move the triggering player to (4, 60, 166).

(0:1) Whenever someone moves,
 (1:35) and they move into position (6, 10),
    (5:19) move the triggering player to (4, 60, 166).

\* NPC Spawns */
(0:0) When everything is starting up,

