*/ 17 - Beach Secret
*
*\

\* Warps */

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 6),
    (5:19) move the triggering player to (22, 23, 13).

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 7),
    (5:19) move the triggering player to (22, 23, 13).

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 8),
    (5:19) move the triggering player to (22, 23, 13).

\* NPC Spawns */
(0:0) When everything is starting up,

