*/ 200 - Estaq stronghold
*
*\

\* Warps */

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 6),
    (5:19) move the triggering player to (2, 12, 68).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 7),
    (5:19) move the triggering player to (2, 12, 68).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 8),
    (5:19) move the triggering player to (2, 12, 68).

\* NPC Spawns */
(0:0) When everything is starting up,

