*/ 211 - Aeven
*
*\

\* Warps */

(0:1) Whenever someone moves,
 (1:35) and they move into position (16, 6),
    (5:19) move the triggering player to (52, 15, 151).

(0:1) Whenever someone moves,
 (1:35) and they move into position (16, 7),
    (5:19) move the triggering player to (52, 15, 151).

\* NPC Spawns */
(0:0) When everything is starting up,
    (5:220) spawn a new NPC 164 at (2, 5) on the map.

