*/ 220 - No name specified
*
*\

\* Warps */

(0:1) Whenever someone moves,
 (1:35) and they move into position (31, 0),
    (5:19) move the triggering player to (40, 15, 210).

(0:1) Whenever someone moves,
 (1:35) and they move into position (6, 1),
    (5:19) move the triggering player to (73, 39, 210).

\* NPC Spawns */
(0:0) When everything is starting up,
    (5:220) spawn a new NPC 144 at (5, 5) on the map.
    (5:220) spawn a new NPC 195 at (31, 5) on the map.

