*/ 223 - Underground Fort
*
*\

\* Warps */

(0:1) Whenever someone moves,
 (1:35) and they move into position (36, 8),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (37, 8),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (38, 8),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (39, 8),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (36, 9),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (37, 9),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (38, 9),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (39, 9),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (36, 10),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (37, 10),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (38, 10),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (32, 32),
    (5:19) move the triggering player to (55, 39, 242).

(0:1) Whenever someone moves,
 (1:35) and they move into position (33, 32),
    (5:19) move the triggering player to (55, 39, 242).

(0:1) Whenever someone moves,
 (1:35) and they move into position (34, 32),
    (5:19) move the triggering player to (55, 39, 242).

(0:1) Whenever someone moves,
 (1:35) and they move into position (54, 32),
    (5:19) move the triggering player to (55, 39, 242).

(0:1) Whenever someone moves,
 (1:35) and they move into position (55, 32),
    (5:19) move the triggering player to (55, 39, 242).

(0:1) Whenever someone moves,
 (1:35) and they move into position (32, 33),
    (5:19) move the triggering player to (55, 39, 242).

(0:1) Whenever someone moves,
 (1:35) and they move into position (33, 33),
    (5:19) move the triggering player to (55, 39, 242).

(0:1) Whenever someone moves,
 (1:35) and they move into position (34, 33),
    (5:19) move the triggering player to (55, 39, 242).

(0:1) Whenever someone moves,
 (1:35) and they move into position (32, 34),
    (5:19) move the triggering player to (55, 39, 242).

(0:1) Whenever someone moves,
 (1:35) and they move into position (33, 34),
    (5:19) move the triggering player to (55, 39, 242).

(0:1) Whenever someone moves,
 (1:35) and they move into position (34, 34),
    (5:19) move the triggering player to (55, 39, 242).

(0:1) Whenever someone moves,
 (1:35) and they move into position (52, 34),
    (5:19) move the triggering player to (55, 39, 242).

(0:1) Whenever someone moves,
 (1:35) and they move into position (57, 34),
    (5:19) move the triggering player to (55, 39, 242).

(0:1) Whenever someone moves,
 (1:35) and they move into position (33, 35),
    (5:19) move the triggering player to (55, 39, 242).

(0:1) Whenever someone moves,
 (1:35) and they move into position (34, 35),
    (5:19) move the triggering player to (55, 39, 242).

(0:1) Whenever someone moves,
 (1:35) and they move into position (52, 35),
    (5:19) move the triggering player to (55, 39, 242).

(0:1) Whenever someone moves,
 (1:35) and they move into position (57, 35),
    (5:19) move the triggering player to (55, 39, 242).

(0:1) Whenever someone moves,
 (1:35) and they move into position (54, 36),
    (5:19) move the triggering player to (55, 39, 242).

(0:1) Whenever someone moves,
 (1:35) and they move into position (55, 36),
    (5:19) move the triggering player to (55, 39, 242).

(0:1) Whenever someone moves,
 (1:35) and they move into position (35, 44),
    (5:19) move the triggering player to (55, 39, 242).

(0:1) Whenever someone moves,
 (1:35) and they move into position (36, 44),
    (5:19) move the triggering player to (55, 39, 242).

(0:1) Whenever someone moves,
 (1:35) and they move into position (37, 44),
    (5:19) move the triggering player to (55, 39, 242).

(0:1) Whenever someone moves,
 (1:35) and they move into position (54, 44),
    (5:19) move the triggering player to (55, 58, 242).

(0:1) Whenever someone moves,
 (1:35) and they move into position (55, 44),
    (5:19) move the triggering player to (55, 58, 242).

(0:1) Whenever someone moves,
 (1:35) and they move into position (56, 44),
    (5:19) move the triggering player to (55, 58, 242).

(0:1) Whenever someone moves,
 (1:35) and they move into position (35, 45),
    (5:19) move the triggering player to (55, 39, 242).

(0:1) Whenever someone moves,
 (1:35) and they move into position (36, 45),
    (5:19) move the triggering player to (55, 39, 242).

(0:1) Whenever someone moves,
 (1:35) and they move into position (37, 45),
    (5:19) move the triggering player to (55, 39, 242).

(0:1) Whenever someone moves,
 (1:35) and they move into position (31, 46),
    (5:19) move the triggering player to (17, 70, 242).

(0:1) Whenever someone moves,
 (1:35) and they move into position (35, 46),
    (5:19) move the triggering player to (55, 39, 242).

(0:1) Whenever someone moves,
 (1:35) and they move into position (36, 46),
    (5:19) move the triggering player to (55, 39, 242).

(0:1) Whenever someone moves,
 (1:35) and they move into position (37, 46),
    (5:19) move the triggering player to (55, 39, 242).

(0:1) Whenever someone moves,
 (1:35) and they move into position (54, 56),
    (5:19) move the triggering player to (55, 42, 242).

(0:1) Whenever someone moves,
 (1:35) and they move into position (55, 56),
    (5:19) move the triggering player to (55, 42, 242).

(0:1) Whenever someone moves,
 (1:35) and they move into position (56, 56),
    (5:19) move the triggering player to (55, 42, 242).

(0:1) Whenever someone moves,
 (1:35) and they move into position (16, 70),
    (5:19) move the triggering player to (32, 46, 242).

\* NPC Spawns */
(0:0) When everything is starting up,

