*/ 229 - No name specified
*
*\

\* Warps */

(0:1) Whenever someone moves,
 (1:35) and they move into position (38, 6),
    (5:19) move the triggering player to (52, 6, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (51, 6),
    (5:19) move the triggering player to (37, 6, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (88, 6),
    (5:19) move the triggering player to (102, 6, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (101, 6),
    (5:19) move the triggering player to (87, 6, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (113, 6),
    (5:19) move the triggering player to (128, 6, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (127, 6),
    (5:19) move the triggering player to (112, 6, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (38, 7),
    (5:19) move the triggering player to (52, 7, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (51, 7),
    (5:19) move the triggering player to (37, 7, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (88, 7),
    (5:19) move the triggering player to (102, 7, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (101, 7),
    (5:19) move the triggering player to (87, 7, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (113, 7),
    (5:19) move the triggering player to (128, 7, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (127, 7),
    (5:19) move the triggering player to (112, 7, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (38, 8),
    (5:19) move the triggering player to (52, 8, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (51, 8),
    (5:19) move the triggering player to (37, 8, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (88, 8),
    (5:19) move the triggering player to (102, 8, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (101, 8),
    (5:19) move the triggering player to (87, 8, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (113, 8),
    (5:19) move the triggering player to (128, 8, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (127, 8),
    (5:19) move the triggering player to (112, 8, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (38, 9),
    (5:19) move the triggering player to (52, 9, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (51, 9),
    (5:19) move the triggering player to (37, 9, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (88, 9),
    (5:19) move the triggering player to (102, 9, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (101, 9),
    (5:19) move the triggering player to (87, 9, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (113, 9),
    (5:19) move the triggering player to (128, 9, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (127, 9),
    (5:19) move the triggering player to (112, 9, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (56, 13),
    (5:19) move the triggering player to (56, 27, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (57, 13),
    (5:19) move the triggering player to (57, 27, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (58, 13),
    (5:19) move the triggering player to (58, 27, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (81, 13),
    (5:19) move the triggering player to (81, 27, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (82, 13),
    (5:19) move the triggering player to (82, 27, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (83, 13),
    (5:19) move the triggering player to (83, 27, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (106, 13),
    (5:19) move the triggering player to (106, 27, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (107, 13),
    (5:19) move the triggering player to (107, 27, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (108, 13),
    (5:19) move the triggering player to (108, 27, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (156, 13),
    (5:19) move the triggering player to (156, 27, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (157, 13),
    (5:19) move the triggering player to (157, 27, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (158, 13),
    (5:19) move the triggering player to (158, 27, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (56, 26),
    (5:19) move the triggering player to (56, 13, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (57, 26),
    (5:19) move the triggering player to (57, 13, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (58, 26),
    (5:19) move the triggering player to (58, 13, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (81, 26),
    (5:19) move the triggering player to (81, 12, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (82, 26),
    (5:19) move the triggering player to (82, 12, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (83, 26),
    (5:19) move the triggering player to (83, 12, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (106, 26),
    (5:19) move the triggering player to (106, 12, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (107, 26),
    (5:19) move the triggering player to (107, 12, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (108, 26),
    (5:19) move the triggering player to (108, 12, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (156, 26),
    (5:19) move the triggering player to (156, 12, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (157, 26),
    (5:19) move the triggering player to (157, 12, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (158, 26),
    (5:19) move the triggering player to (158, 12, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (63, 31),
    (5:19) move the triggering player to (77, 31, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (76, 31),
    (5:19) move the triggering player to (62, 31, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (88, 31),
    (5:19) move the triggering player to (102, 31, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (101, 31),
    (5:19) move the triggering player to (87, 31, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (63, 32),
    (5:19) move the triggering player to (77, 32, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (76, 32),
    (5:19) move the triggering player to (62, 32, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (88, 32),
    (5:19) move the triggering player to (102, 32, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (101, 32),
    (5:19) move the triggering player to (87, 32, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (63, 33),
    (5:19) move the triggering player to (77, 33, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (76, 33),
    (5:19) move the triggering player to (62, 33, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (88, 33),
    (5:19) move the triggering player to (102, 33, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (101, 33),
    (5:19) move the triggering player to (87, 33, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (131, 38),
    (5:19) move the triggering player to (131, 52, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (132, 38),
    (5:19) move the triggering player to (132, 52, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (133, 38),
    (5:19) move the triggering player to (133, 52, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (131, 51),
    (5:19) move the triggering player to (131, 38, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (132, 51),
    (5:19) move the triggering player to (132, 38, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (133, 51),
    (5:19) move the triggering player to (133, 38, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 55),
    (5:19) move the triggering player to (27, 56, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 56),
    (5:19) move the triggering player to (27, 57, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (26, 56),
    (5:19) move the triggering player to (12, 55, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (63, 56),
    (5:19) move the triggering player to (77, 56, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (76, 56),
    (5:19) move the triggering player to (62, 56, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (88, 56),
    (5:19) move the triggering player to (102, 56, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (101, 56),
    (5:19) move the triggering player to (87, 56, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (113, 56),
    (5:19) move the triggering player to (127, 56, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (126, 56),
    (5:19) move the triggering player to (112, 56, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 57),
    (5:19) move the triggering player to (27, 58, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (26, 57),
    (5:19) move the triggering player to (12, 56, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (63, 57),
    (5:19) move the triggering player to (77, 57, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (76, 57),
    (5:19) move the triggering player to (62, 57, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (88, 57),
    (5:19) move the triggering player to (102, 57, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (101, 57),
    (5:19) move the triggering player to (87, 57, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (113, 57),
    (5:19) move the triggering player to (127, 57, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (126, 57),
    (5:19) move the triggering player to (112, 57, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (26, 58),
    (5:19) move the triggering player to (12, 57, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (63, 58),
    (5:19) move the triggering player to (77, 58, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (76, 58),
    (5:19) move the triggering player to (62, 58, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (88, 58),
    (5:19) move the triggering player to (102, 58, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (101, 58),
    (5:19) move the triggering player to (87, 58, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (113, 58),
    (5:19) move the triggering player to (127, 58, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (126, 58),
    (5:19) move the triggering player to (112, 58, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (56, 63),
    (5:19) move the triggering player to (56, 77, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (57, 63),
    (5:19) move the triggering player to (57, 77, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (58, 63),
    (5:19) move the triggering player to (58, 77, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (81, 63),
    (5:19) move the triggering player to (81, 78, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (82, 63),
    (5:19) move the triggering player to (82, 78, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (83, 63),
    (5:19) move the triggering player to (83, 78, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (131, 63),
    (5:19) move the triggering player to (131, 77, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (132, 63),
    (5:19) move the triggering player to (132, 77, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (133, 63),
    (5:19) move the triggering player to (133, 77, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (156, 63),
    (5:19) move the triggering player to (156, 77, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (157, 63),
    (5:19) move the triggering player to (157, 77, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (158, 63),
    (5:19) move the triggering player to (158, 77, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (56, 76),
    (5:19) move the triggering player to (56, 62, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (57, 76),
    (5:19) move the triggering player to (57, 62, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (58, 76),
    (5:19) move the triggering player to (58, 62, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (81, 76),
    (5:19) move the triggering player to (81, 62, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (82, 76),
    (5:19) move the triggering player to (82, 62, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (83, 76),
    (5:19) move the triggering player to (83, 62, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (131, 76),
    (5:19) move the triggering player to (131, 62, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (132, 76),
    (5:19) move the triggering player to (132, 62, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (133, 76),
    (5:19) move the triggering player to (133, 62, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (156, 76),
    (5:19) move the triggering player to (156, 62, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (157, 76),
    (5:19) move the triggering player to (157, 62, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (158, 76),
    (5:19) move the triggering player to (158, 62, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (38, 81),
    (5:19) move the triggering player to (52, 81, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (51, 81),
    (5:19) move the triggering player to (37, 81, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (38, 82),
    (5:19) move the triggering player to (52, 82, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (51, 82),
    (5:19) move the triggering player to (37, 82, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (38, 83),
    (5:19) move the triggering player to (52, 83, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (51, 83),
    (5:19) move the triggering player to (37, 83, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (7, 88),
    (5:19) move the triggering player to (7, 102, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (8, 88),
    (5:19) move the triggering player to (8, 102, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (9, 88),
    (5:19) move the triggering player to (9, 102, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (56, 88),
    (5:19) move the triggering player to (56, 102, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (57, 88),
    (5:19) move the triggering player to (57, 102, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (58, 88),
    (5:19) move the triggering player to (58, 102, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (106, 88),
    (5:19) move the triggering player to (106, 102, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (107, 88),
    (5:19) move the triggering player to (107, 102, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (108, 88),
    (5:19) move the triggering player to (108, 102, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (156, 88),
    (5:19) move the triggering player to (156, 102, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (157, 88),
    (5:19) move the triggering player to (157, 102, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (158, 88),
    (5:19) move the triggering player to (158, 102, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (7, 101),
    (5:19) move the triggering player to (7, 87, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (8, 101),
    (5:19) move the triggering player to (8, 87, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (9, 101),
    (5:19) move the triggering player to (9, 87, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (56, 101),
    (5:19) move the triggering player to (58, 87, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (57, 101),
    (5:19) move the triggering player to (59, 87, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (58, 101),
    (5:19) move the triggering player to (60, 87, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (106, 101),
    (5:19) move the triggering player to (106, 87, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (107, 101),
    (5:19) move the triggering player to (107, 87, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (108, 101),
    (5:19) move the triggering player to (108, 87, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (131, 101),
    (5:19) move the triggering player to (106, 112, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (132, 101),
    (5:19) move the triggering player to (107, 112, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (133, 101),
    (5:19) move the triggering player to (108, 112, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (156, 101),
    (5:19) move the triggering player to (156, 87, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (157, 101),
    (5:19) move the triggering player to (157, 87, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (158, 101),
    (5:19) move the triggering player to (158, 87, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 106),
    (5:19) move the triggering player to (27, 106, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (26, 106),
    (5:19) move the triggering player to (12, 106, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (101, 106),
    (5:19) move the triggering player to (137, 106, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (113, 106),
    (5:19) move the triggering player to (127, 106, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (126, 106),
    (5:19) move the triggering player to (112, 106, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (138, 106),
    (5:19) move the triggering player to (152, 106, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (151, 106),
    (5:19) move the triggering player to (137, 106, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 107),
    (5:19) move the triggering player to (27, 107, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (26, 107),
    (5:19) move the triggering player to (12, 107, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (101, 107),
    (5:19) move the triggering player to (137, 107, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (113, 107),
    (5:19) move the triggering player to (127, 107, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (126, 107),
    (5:19) move the triggering player to (112, 107, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (138, 107),
    (5:19) move the triggering player to (152, 107, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (151, 107),
    (5:19) move the triggering player to (137, 107, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 108),
    (5:19) move the triggering player to (27, 108, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (26, 108),
    (5:19) move the triggering player to (12, 108, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (101, 108),
    (5:19) move the triggering player to (137, 108, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (113, 108),
    (5:19) move the triggering player to (127, 108, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (126, 108),
    (5:19) move the triggering player to (112, 108, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (138, 108),
    (5:19) move the triggering player to (152, 108, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (151, 108),
    (5:19) move the triggering player to (137, 108, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (81, 113),
    (5:19) move the triggering player to (26, 34, 228).

(0:1) Whenever someone moves,
 (1:35) and they move into position (82, 113),
    (5:19) move the triggering player to (26, 34, 228).

(0:1) Whenever someone moves,
 (1:35) and they move into position (83, 113),
    (5:19) move the triggering player to (26, 34, 228).

(0:1) Whenever someone moves,
 (1:35) and they move into position (106, 113),
    (5:19) move the triggering player to (131, 102, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (107, 113),
    (5:19) move the triggering player to (132, 102, 229).

(0:1) Whenever someone moves,
 (1:35) and they move into position (108, 113),
    (5:19) move the triggering player to (133, 102, 229).

\* NPC Spawns */
(0:0) When everything is starting up,
    (5:220) spawn a new NPC 2 at (81, 86) on the map.
    (5:220) spawn a new NPC 2 at (81, 99) on the map.
    (5:220) spawn a new NPC 180 at (32, 58) on the map.
    (5:220) spawn a new NPC 181 at (7, 108) on the map.
    (5:220) spawn a new NPC 181 at (33, 108) on the map.
    (5:220) spawn a new NPC 191 at (33, 87) on the map.
    (5:220) spawn a new NPC 181 at (58, 109) on the map.
    (5:220) spawn a new NPC 181 at (107, 82) on the map.
    (5:220) spawn a new NPC 181 at (126, 82) on the map.
    (5:220) spawn a new NPC 191 at (158, 5) on the map.
    (5:220) spawn a new NPC 181 at (156, 50) on the map.
    (5:220) spawn a new NPC 181 at (156, 50) on the map.
    (5:220) spawn a new NPC 181 at (153, 8) on the map.
    (5:220) spawn a new NPC 181 at (139, 9) on the map.
    (5:220) spawn a new NPC 181 at (133, 33) on the map.
    (5:220) spawn a new NPC 181 at (83, 32) on the map.
    (5:220) spawn a new NPC 181 at (106, 32) on the map.
    (5:220) spawn a new NPC 2 at (14, 24) on the map.
    (5:220) spawn a new NPC 2 at (30, 15) on the map.
    (5:220) spawn a new NPC 2 at (142, 9) on the map.
    (5:220) spawn a new NPC 2 at (156, 40) on the map.
    (5:220) spawn a new NPC 2 at (58, 58) on the map.
    (5:220) spawn a new NPC 2 at (32, 99) on the map.
    (5:220) spawn a new NPC 174 at (12, 12) on the map.
    (5:220) spawn a new NPC 174 at (28, 23) on the map.
    (5:220) spawn a new NPC 174 at (11, 29) on the map.

