*/ 230 - Illusion Tombes
*
*\

\* Warps */

(0:1) Whenever someone moves,
 (1:35) and they move into position (6, 1),
    (5:19) move the triggering player to (5, 62, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (7, 1),
    (5:19) move the triggering player to (6, 62, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (8, 1),
    (5:19) move the triggering player to (7, 62, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (9, 1),
    (5:19) move the triggering player to (8, 62, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (10, 1),
    (5:19) move the triggering player to (9, 62, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (30, 1),
    (5:19) move the triggering player to (30, 62, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (31, 1),
    (5:19) move the triggering player to (31, 62, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (32, 1),
    (5:19) move the triggering player to (32, 62, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (33, 1),
    (5:19) move the triggering player to (33, 62, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (34, 1),
    (5:19) move the triggering player to (34, 62, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (55, 1),
    (5:19) move the triggering player to (55, 62, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (56, 1),
    (5:19) move the triggering player to (56, 62, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (57, 1),
    (5:19) move the triggering player to (57, 62, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (58, 1),
    (5:19) move the triggering player to (58, 62, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (59, 1),
    (5:19) move the triggering player to (59, 62, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (2, 5),
    (5:19) move the triggering player to (62, 5, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (14, 5),
    (5:19) move the triggering player to (27, 5, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (26, 5),
    (5:19) move the triggering player to (13, 5, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (38, 5),
    (5:19) move the triggering player to (52, 5, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (51, 5),
    (5:19) move the triggering player to (37, 6, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (63, 5),
    (5:19) move the triggering player to (3, 5, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (2, 6),
    (5:19) move the triggering player to (62, 6, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (14, 6),
    (5:19) move the triggering player to (27, 6, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (26, 6),
    (5:19) move the triggering player to (13, 6, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (38, 6),
    (5:19) move the triggering player to (52, 6, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (51, 6),
    (5:19) move the triggering player to (37, 7, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (63, 6),
    (5:19) move the triggering player to (3, 6, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (2, 7),
    (5:19) move the triggering player to (62, 7, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (14, 7),
    (5:19) move the triggering player to (27, 7, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (26, 7),
    (5:19) move the triggering player to (13, 7, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (38, 7),
    (5:19) move the triggering player to (52, 7, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (51, 7),
    (5:19) move the triggering player to (37, 8, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (63, 7),
    (5:19) move the triggering player to (3, 7, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (2, 8),
    (5:19) move the triggering player to (62, 8, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (14, 8),
    (5:19) move the triggering player to (27, 8, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (26, 8),
    (5:19) move the triggering player to (13, 8, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (38, 8),
    (5:19) move the triggering player to (52, 8, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (51, 8),
    (5:19) move the triggering player to (37, 9, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (63, 8),
    (5:19) move the triggering player to (3, 8, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (2, 9),
    (5:19) move the triggering player to (62, 9, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (14, 9),
    (5:19) move the triggering player to (27, 9, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (26, 9),
    (5:19) move the triggering player to (13, 9, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (38, 9),
    (5:19) move the triggering player to (52, 9, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (51, 9),
    (5:19) move the triggering player to (37, 10, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (63, 9),
    (5:19) move the triggering player to (3, 9, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (6, 13),
    (5:19) move the triggering player to (7, 2, 231).

(0:1) Whenever someone moves,
 (1:35) and they move into position (7, 13),
    (5:19) move the triggering player to (8, 2, 231).

(0:1) Whenever someone moves,
 (1:35) and they move into position (8, 13),
    (5:19) move the triggering player to (9, 2, 231).

(0:1) Whenever someone moves,
 (1:35) and they move into position (9, 13),
    (5:19) move the triggering player to (10, 2, 231).

(0:1) Whenever someone moves,
 (1:35) and they move into position (10, 13),
    (5:19) move the triggering player to (11, 2, 231).

(0:1) Whenever someone moves,
 (1:35) and they move into position (30, 13),
    (5:19) move the triggering player to (30, 27, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (31, 13),
    (5:19) move the triggering player to (31, 27, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (32, 13),
    (5:19) move the triggering player to (32, 27, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (33, 13),
    (5:19) move the triggering player to (33, 27, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (34, 13),
    (5:19) move the triggering player to (34, 27, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (55, 13),
    (5:19) move the triggering player to (55, 27, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (56, 13),
    (5:19) move the triggering player to (56, 27, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (57, 13),
    (5:19) move the triggering player to (57, 27, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (58, 13),
    (5:19) move the triggering player to (58, 27, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (59, 13),
    (5:19) move the triggering player to (59, 27, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (5, 26),
    (5:19) move the triggering player to (6, 12, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (6, 26),
    (5:19) move the triggering player to (7, 12, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (7, 26),
    (5:19) move the triggering player to (8, 12, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (8, 26),
    (5:19) move the triggering player to (9, 12, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (30, 26),
    (5:19) move the triggering player to (30, 12, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (31, 26),
    (5:19) move the triggering player to (31, 12, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (32, 26),
    (5:19) move the triggering player to (32, 12, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (33, 26),
    (5:19) move the triggering player to (33, 12, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (34, 26),
    (5:19) move the triggering player to (34, 12, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (55, 26),
    (5:19) move the triggering player to (55, 12, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (56, 26),
    (5:19) move the triggering player to (56, 12, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (57, 26),
    (5:19) move the triggering player to (57, 12, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (58, 26),
    (5:19) move the triggering player to (58, 12, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (59, 26),
    (5:19) move the triggering player to (59, 12, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (1, 30),
    (5:19) move the triggering player to (62, 30, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 30),
    (5:19) move the triggering player to (27, 30, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (26, 30),
    (5:19) move the triggering player to (12, 30, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (38, 30),
    (5:19) move the triggering player to (52, 30, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (51, 30),
    (5:19) move the triggering player to (37, 30, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (63, 30),
    (5:19) move the triggering player to (2, 30, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (1, 31),
    (5:19) move the triggering player to (62, 31, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 31),
    (5:19) move the triggering player to (27, 31, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (26, 31),
    (5:19) move the triggering player to (12, 31, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (38, 31),
    (5:19) move the triggering player to (52, 31, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (51, 31),
    (5:19) move the triggering player to (37, 31, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (63, 31),
    (5:19) move the triggering player to (2, 31, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (1, 32),
    (5:19) move the triggering player to (62, 32, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 32),
    (5:19) move the triggering player to (27, 32, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (26, 32),
    (5:19) move the triggering player to (12, 32, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (38, 32),
    (5:19) move the triggering player to (52, 32, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (51, 32),
    (5:19) move the triggering player to (37, 33, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (63, 32),
    (5:19) move the triggering player to (2, 32, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (1, 33),
    (5:19) move the triggering player to (62, 33, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 33),
    (5:19) move the triggering player to (27, 33, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (26, 33),
    (5:19) move the triggering player to (12, 33, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (38, 33),
    (5:19) move the triggering player to (52, 33, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (51, 33),
    (5:19) move the triggering player to (37, 34, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (63, 33),
    (5:19) move the triggering player to (2, 33, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (1, 34),
    (5:19) move the triggering player to (62, 34, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (26, 34),
    (5:19) move the triggering player to (12, 34, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (38, 34),
    (5:19) move the triggering player to (52, 34, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (51, 34),
    (5:19) move the triggering player to (37, 35, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (63, 34),
    (5:19) move the triggering player to (2, 34, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (5, 38),
    (5:19) move the triggering player to (5, 52, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (6, 38),
    (5:19) move the triggering player to (6, 52, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (7, 38),
    (5:19) move the triggering player to (7, 52, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (8, 38),
    (5:19) move the triggering player to (8, 52, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (9, 38),
    (5:19) move the triggering player to (9, 52, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (30, 38),
    (5:19) move the triggering player to (30, 52, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (31, 38),
    (5:19) move the triggering player to (31, 52, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (32, 38),
    (5:19) move the triggering player to (32, 52, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (33, 38),
    (5:19) move the triggering player to (33, 52, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (34, 38),
    (5:19) move the triggering player to (34, 52, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (55, 38),
    (5:19) move the triggering player to (55, 52, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (56, 38),
    (5:19) move the triggering player to (56, 52, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (57, 38),
    (5:19) move the triggering player to (57, 52, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (58, 38),
    (5:19) move the triggering player to (58, 52, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (59, 38),
    (5:19) move the triggering player to (59, 52, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (5, 51),
    (5:19) move the triggering player to (5, 37, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (6, 51),
    (5:19) move the triggering player to (6, 37, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (7, 51),
    (5:19) move the triggering player to (7, 37, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (8, 51),
    (5:19) move the triggering player to (8, 37, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (9, 51),
    (5:19) move the triggering player to (9, 37, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (30, 51),
    (5:19) move the triggering player to (30, 37, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (31, 51),
    (5:19) move the triggering player to (31, 37, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (32, 51),
    (5:19) move the triggering player to (32, 37, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (33, 51),
    (5:19) move the triggering player to (33, 37, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (34, 51),
    (5:19) move the triggering player to (34, 37, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (55, 51),
    (5:19) move the triggering player to (55, 37, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (56, 51),
    (5:19) move the triggering player to (56, 37, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (57, 51),
    (5:19) move the triggering player to (57, 37, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (58, 51),
    (5:19) move the triggering player to (58, 37, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (59, 51),
    (5:19) move the triggering player to (59, 37, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (1, 55),
    (5:19) move the triggering player to (62, 55, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 55),
    (5:19) move the triggering player to (27, 55, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (26, 55),
    (5:19) move the triggering player to (13, 55, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (38, 55),
    (5:19) move the triggering player to (52, 55, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (51, 55),
    (5:19) move the triggering player to (37, 55, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (63, 55),
    (5:19) move the triggering player to (2, 55, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (1, 56),
    (5:19) move the triggering player to (62, 56, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 56),
    (5:19) move the triggering player to (27, 56, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (26, 56),
    (5:19) move the triggering player to (13, 56, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (38, 56),
    (5:19) move the triggering player to (52, 56, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (51, 56),
    (5:19) move the triggering player to (37, 56, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (63, 56),
    (5:19) move the triggering player to (2, 56, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (1, 57),
    (5:19) move the triggering player to (62, 57, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 57),
    (5:19) move the triggering player to (27, 57, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (26, 57),
    (5:19) move the triggering player to (13, 57, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (38, 57),
    (5:19) move the triggering player to (52, 57, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (51, 57),
    (5:19) move the triggering player to (37, 57, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (63, 57),
    (5:19) move the triggering player to (2, 57, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (1, 58),
    (5:19) move the triggering player to (62, 58, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 58),
    (5:19) move the triggering player to (27, 58, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (26, 58),
    (5:19) move the triggering player to (13, 58, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (38, 58),
    (5:19) move the triggering player to (52, 58, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (51, 58),
    (5:19) move the triggering player to (37, 58, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (63, 58),
    (5:19) move the triggering player to (2, 58, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (1, 59),
    (5:19) move the triggering player to (62, 59, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 59),
    (5:19) move the triggering player to (27, 59, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (26, 59),
    (5:19) move the triggering player to (13, 59, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (38, 59),
    (5:19) move the triggering player to (52, 59, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (51, 59),
    (5:19) move the triggering player to (37, 59, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (63, 59),
    (5:19) move the triggering player to (2, 59, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (5, 63),
    (5:19) move the triggering player to (6, 28, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (6, 63),
    (5:19) move the triggering player to (7, 28, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (7, 63),
    (5:19) move the triggering player to (8, 28, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (8, 63),
    (5:19) move the triggering player to (9, 28, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (9, 63),
    (5:19) move the triggering player to (10, 28, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (30, 63),
    (5:19) move the triggering player to (31, 16, 228).

(0:1) Whenever someone moves,
 (1:35) and they move into position (31, 63),
    (5:19) move the triggering player to (31, 16, 228).

(0:1) Whenever someone moves,
 (1:35) and they move into position (32, 63),
    (5:19) move the triggering player to (31, 16, 228).

(0:1) Whenever someone moves,
 (1:35) and they move into position (33, 63),
    (5:19) move the triggering player to (31, 16, 228).

(0:1) Whenever someone moves,
 (1:35) and they move into position (34, 63),
    (5:19) move the triggering player to (31, 16, 228).

(0:1) Whenever someone moves,
 (1:35) and they move into position (55, 63),
    (5:19) move the triggering player to (55, 2, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (56, 63),
    (5:19) move the triggering player to (56, 2, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (57, 63),
    (5:19) move the triggering player to (57, 2, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (58, 63),
    (5:19) move the triggering player to (58, 2, 230).

(0:1) Whenever someone moves,
 (1:35) and they move into position (59, 63),
    (5:19) move the triggering player to (59, 2, 230).

\* NPC Spawns */
(0:0) When everything is starting up,

