*/ 253 - No name specified
*
*\

\* Warps */

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 6),
    (5:19) move the triggering player to (39, 5, 7).

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 7),
    (5:19) move the triggering player to (39, 5, 7).

\* NPC Spawns */
(0:0) When everything is starting up,
    (5:220) spawn a new NPC 240 at (6, 6) on the map.
    (5:220) spawn a new NPC 252 at (6, 6) on the map.

