*/ 264 - No name specified
*
*\

\* NPC Spawns */
(0:0) When everything is starting up,
    (5:220) spawn a new NPC 239 at (0, 0) on the map.
    (5:220) spawn a new NPC 240 at (0, 0) on the map.
    (5:220) spawn a new NPC 241 at (0, 0) on the map.
    (5:220) spawn a new NPC 242 at (0, 0) on the map.
    (5:220) spawn a new NPC 243 at (0, 0) on the map.
    (5:220) spawn a new NPC 244 at (0, 0) on the map.

