*/ 27 - No name specified
*
*\

\* Warps */

(0:1) Whenever someone moves,
 (1:35) and they move into position (5, 14),
    (5:19) move the triggering player to (11, 73, 5).

(0:1) Whenever someone moves,
 (1:35) and they move into position (6, 14),
    (5:19) move the triggering player to (11, 73, 5).

\* NPC Spawns */
(0:0) When everything is starting up,
    (5:220) spawn a new NPC 24 at (5, 2) on the map.

