*/ 272 - Monkey Island
*
*\

\* Warps */

(0:1) Whenever someone moves,
 (1:35) and they move into position (10, 5),
    (5:19) move the triggering player to (51, 10, 271).

(0:1) Whenever someone moves,
 (1:35) and they move into position (10, 6),
    (5:19) move the triggering player to (51, 10, 271).

\* NPC Spawns */
(0:0) When everything is starting up,
    (5:220) spawn a new NPC 250 at (6, 6) on the map.

