*/ 278 - No name specified
*
*\

\* Warps */

(0:1) Whenever someone moves,
 (1:35) and they move into position (3, 0),
    (5:19) move the triggering player to (2, 3, 3).

\* NPC Spawns */
(0:0) When everything is starting up,
    (5:220) spawn a new NPC 270 at (5, 4) on the map.
    (5:220) spawn a new NPC 270 at (8, 9) on the map.
    (5:220) spawn a new NPC 270 at (3, 9) on the map.
    (5:220) spawn a new NPC 270 at (8, 4) on the map.
    (5:220) spawn a new NPC 270 at (5, 5) on the map.

