*/ 283 - Aeven Tailor
*
*\

\* Warps */

(0:1) Whenever someone moves,
 (1:35) and they move into position (5, 12),
    (5:19) move the triggering player to (67, 75, 5).

(0:1) Whenever someone moves,
 (1:35) and they move into position (6, 12),
    (5:19) move the triggering player to (67, 75, 5).

\* NPC Spawns */
(0:0) When everything is starting up,
    (5:220) spawn a new NPC 304 at (2, 1) on the map.

