*/ 3 - Farmer house
*
*\

\* Warps */

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 8),
    (5:19) move the triggering player to (6, 40, 2).

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 9),
    (5:19) move the triggering player to (6, 40, 2).

\* NPC Spawns */
(0:0) When everything is starting up,
    (5:220) spawn a new NPC 2 at (4, 6) on the map.
    (5:220) spawn a new NPC 269 at (6, 6) on the map.

