*/ 31 - Void
*
*\

\* Warps */

(0:1) Whenever someone moves,
 (1:35) and they move into position (11, 0),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 0),
    (5:19) move the triggering player to (12, 16, 31).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 0),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (11, 1),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 1),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (11, 2),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 2),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (11, 3),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 3),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (11, 4),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 4),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (11, 5),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 5),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (6, 6),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (7, 6),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (8, 6),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (9, 6),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (10, 6),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (11, 6),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 6),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (14, 6),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (15, 6),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (16, 6),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (17, 6),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (18, 6),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (6, 7),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (10, 7),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (11, 7),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 7),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (14, 7),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (15, 7),
    (5:19) move the triggering player to (9, 7, 31).

(0:1) Whenever someone moves,
 (1:35) and they move into position (18, 7),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (6, 8),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (8, 8),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (9, 8),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (10, 8),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (11, 8),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 8),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (14, 8),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (15, 8),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (16, 8),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (18, 8),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (6, 9),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (7, 9),
    (5:19) move the triggering player to (12, 12, 36).

(0:1) Whenever someone moves,
 (1:35) and they move into position (8, 9),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (9, 9),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (10, 9),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (11, 9),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 9),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (14, 9),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (15, 9),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (16, 9),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (18, 9),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (6, 10),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (7, 10),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (8, 10),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (9, 10),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (15, 10),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (16, 10),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (17, 10),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (18, 10),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (24, 10),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 11),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (1, 11),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (2, 11),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (3, 11),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (4, 11),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (5, 11),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (6, 11),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (7, 11),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (8, 11),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (9, 11),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (15, 11),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (16, 11),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (17, 11),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (18, 11),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (19, 11),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (20, 11),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (21, 11),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (22, 11),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (23, 11),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (24, 11),
    (5:19) move the triggering player to (8, 12, 31).

(0:1) Whenever someone moves,
 (1:35) and they move into position (9, 12),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (15, 12),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 13),
    (5:19) move the triggering player to (7, 15, 31).

(0:1) Whenever someone moves,
 (1:35) and they move into position (1, 13),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (2, 13),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (3, 13),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (4, 13),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (5, 13),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (6, 13),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (7, 13),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (8, 13),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (9, 13),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (15, 13),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (16, 13),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (17, 13),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (18, 13),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (19, 13),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (20, 13),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (21, 13),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (22, 13),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (24, 13),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 14),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (6, 14),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (7, 14),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (8, 14),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (9, 14),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (15, 14),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (16, 14),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (17, 14),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (18, 14),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (24, 14),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (6, 15),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (8, 15),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (9, 15),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (10, 15),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (11, 15),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 15),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 15),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (14, 15),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (15, 15),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (16, 15),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (17, 15),
    (5:19) move the triggering player to (17, 9, 31).

(0:1) Whenever someone moves,
 (1:35) and they move into position (18, 15),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (20, 15),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (21, 15),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (22, 15),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (23, 15),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (24, 15),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (6, 16),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (8, 16),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (9, 16),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (10, 16),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (11, 16),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 16),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (14, 16),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (15, 16),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (16, 16),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (18, 16),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (6, 17),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (9, 17),
    (5:19) move the triggering player to (15, 17, 31).

(0:1) Whenever someone moves,
 (1:35) and they move into position (10, 17),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (11, 17),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 17),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (14, 17),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (18, 17),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (19, 17),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (20, 17),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (21, 17),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (22, 17),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (23, 17),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (6, 18),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (7, 18),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (8, 18),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (9, 18),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (10, 18),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (11, 18),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 18),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (14, 18),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (15, 18),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (16, 18),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (17, 18),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (18, 18),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (11, 19),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 19),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (14, 19),
    (5:19) move the triggering player to (11, 23, 44).

(0:1) Whenever someone moves,
 (1:35) and they move into position (20, 19),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (21, 19),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (22, 19),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (23, 19),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (24, 19),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (11, 20),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 20),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (14, 20),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (15, 20),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (16, 20),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (17, 20),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (18, 20),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (19, 20),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (20, 20),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (11, 21),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 21),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (11, 22),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 22),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (11, 23),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 23),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (14, 23),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (11, 24),
    (5:19) move the triggering player to (6, 6, 32).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 24),
    (5:19) move the triggering player to (16, 12, 31).

(0:1) Whenever someone moves,
 (1:35) and they move into position (14, 24),
    (5:19) move the triggering player to (6, 6, 32).

\* NPC Spawns */
(0:0) When everything is starting up,

