*/ 44 - No name specified
*
*\

\* Warps */

(0:1) Whenever someone moves,
 (1:35) and they move into position (15, 0),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (17, 0),
    (5:19) move the triggering player to (16, 0, 44).

(0:1) Whenever someone moves,
 (1:35) and they move into position (19, 0),
    (5:19) move the triggering player to (17, 0, 44).

(0:1) Whenever someone moves,
 (1:35) and they move into position (21, 0),
    (5:19) move the triggering player to (19, 0, 44).

(0:1) Whenever someone moves,
 (1:35) and they move into position (23, 0),
    (5:19) move the triggering player to (21, 0, 44).

(0:1) Whenever someone moves,
 (1:35) and they move into position (24, 0),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (15, 1),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (17, 1),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (18, 1),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (19, 1),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (20, 1),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (21, 1),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (22, 1),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (24, 1),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 2),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (1, 2),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (2, 2),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (3, 2),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (4, 2),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (5, 2),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (6, 2),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (7, 2),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (8, 2),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (9, 2),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (10, 2),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (11, 2),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 2),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 2),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (14, 2),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (15, 2),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (17, 2),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (22, 2),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (24, 2),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 3),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (2, 3),
    (5:19) move the triggering player to (0, 3, 44).

(0:1) Whenever someone moves,
 (1:35) and they move into position (4, 3),
    (5:19) move the triggering player to (2, 3, 44).

(0:1) Whenever someone moves,
 (1:35) and they move into position (6, 3),
    (5:19) move the triggering player to (4, 3, 44).

(0:1) Whenever someone moves,
 (1:35) and they move into position (8, 3),
    (5:19) move the triggering player to (6, 3, 44).

(0:1) Whenever someone moves,
 (1:35) and they move into position (10, 3),
    (5:19) move the triggering player to (8, 3, 44).

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 3),
    (5:19) move the triggering player to (10, 3, 44).

(0:1) Whenever someone moves,
 (1:35) and they move into position (14, 3),
    (5:19) move the triggering player to (12, 3, 44).

(0:1) Whenever someone moves,
 (1:35) and they move into position (16, 3),
    (5:19) move the triggering player to (14, 3, 44).

(0:1) Whenever someone moves,
 (1:35) and they move into position (17, 3),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (22, 3),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (24, 3),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 4),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (2, 4),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (3, 4),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (4, 4),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (5, 4),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (6, 4),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (7, 4),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (8, 4),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (9, 4),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (10, 4),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (11, 4),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 4),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 4),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (14, 4),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (15, 4),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (16, 4),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (17, 4),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (22, 4),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (24, 4),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 5),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (2, 5),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (22, 5),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (24, 5),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 6),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (2, 6),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (22, 6),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (24, 6),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 7),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (2, 7),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (22, 7),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (24, 7),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 8),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (2, 8),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (15, 8),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (16, 8),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (17, 8),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (18, 8),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (19, 8),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (20, 8),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (21, 8),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (22, 8),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (24, 8),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 9),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (2, 9),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (15, 9),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (24, 9),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 10),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (2, 10),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (15, 10),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (17, 10),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (18, 10),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (19, 10),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (20, 10),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (21, 10),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (22, 10),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (23, 10),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (24, 10),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 11),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (2, 11),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (15, 11),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (17, 11),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 12),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (2, 12),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (15, 12),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (17, 12),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 13),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (2, 13),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (15, 13),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (17, 13),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 14),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (1, 14),
    (5:19) move the triggering player to (4, 15, 44).

(0:1) Whenever someone moves,
 (1:35) and they move into position (2, 14),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (3, 14),
    (5:19) move the triggering player to (1, 15, 44).

(0:1) Whenever someone moves,
 (1:35) and they move into position (4, 14),
    (5:19) move the triggering player to (1, 15, 44).

(0:1) Whenever someone moves,
 (1:35) and they move into position (5, 14),
    (5:19) move the triggering player to (1, 15, 44).

(0:1) Whenever someone moves,
 (1:35) and they move into position (10, 14),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (11, 14),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 14),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 14),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (14, 14),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (15, 14),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (17, 14),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 15),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (2, 15),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (3, 15),
    (5:19) move the triggering player to (1, 15, 44).

(0:1) Whenever someone moves,
 (1:35) and they move into position (5, 15),
    (5:19) move the triggering player to (1, 15, 44).

(0:1) Whenever someone moves,
 (1:35) and they move into position (10, 15),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (17, 15),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 16),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (2, 16),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (3, 16),
    (5:19) move the triggering player to (1, 15, 44).

(0:1) Whenever someone moves,
 (1:35) and they move into position (4, 16),
    (5:19) move the triggering player to (1, 15, 44).

(0:1) Whenever someone moves,
 (1:35) and they move into position (5, 16),
    (5:19) move the triggering player to (1, 15, 44).

(0:1) Whenever someone moves,
 (1:35) and they move into position (10, 16),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 16),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 16),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (14, 16),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (15, 16),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (16, 16),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (17, 16),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 17),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (2, 17),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (10, 17),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 17),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 18),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (2, 18),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (10, 18),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 18),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 19),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (2, 19),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (10, 19),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 19),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 20),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (2, 20),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (10, 20),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 20),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 21),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (2, 21),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (10, 21),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 21),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 22),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (2, 22),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (10, 22),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (11, 22),
    (5:19) move the triggering player to (11, 21, 44).

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 22),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 23),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (2, 23),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (10, 23),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (11, 23),
    (5:19) move the triggering player to (11, 22, 44).

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 23),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 24),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (1, 24),
    (5:19) move the triggering player to (12, 12, 45).

(0:1) Whenever someone moves,
 (1:35) and they move into position (2, 24),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (10, 24),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (11, 24),
    (5:19) move the triggering player to (0, 0, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 24),
    (5:19) move the triggering player to (0, 0, 24).

\* NPC Spawns */
(0:0) When everything is starting up,

