*/ 47 - Castle maze
*
*\

\* Warps */

(0:1) Whenever someone moves,
 (1:35) and they move into position (106, 4),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (107, 4),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (108, 4),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (109, 4),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (110, 4),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (111, 4),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (112, 4),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (113, 4),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (114, 4),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (115, 4),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (116, 4),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (117, 4),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (118, 4),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (119, 4),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (168, 4),
    (5:19) move the triggering player to (162, 11, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (170, 4),
    (5:19) move the triggering player to (162, 11, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (174, 4),
    (5:19) move the triggering player to (162, 11, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (176, 4),
    (5:19) move the triggering player to (162, 11, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (178, 4),
    (5:19) move the triggering player to (162, 11, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (106, 5),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (119, 5),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (106, 6),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (108, 6),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (109, 6),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (110, 6),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (111, 6),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (112, 6),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (113, 6),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (114, 6),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (115, 6),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (116, 6),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (117, 6),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (119, 6),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (170, 6),
    (5:19) move the triggering player to (162, 11, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (172, 6),
    (5:19) move the triggering player to (162, 11, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (174, 6),
    (5:19) move the triggering player to (162, 11, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (176, 6),
    (5:19) move the triggering player to (162, 11, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (178, 6),
    (5:19) move the triggering player to (162, 11, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (106, 7),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (108, 7),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (117, 7),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (119, 7),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (106, 8),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (108, 8),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (110, 8),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (111, 8),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (112, 8),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (113, 8),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (114, 8),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (115, 8),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (117, 8),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (119, 8),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (168, 8),
    (5:19) move the triggering player to (162, 11, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (170, 8),
    (5:19) move the triggering player to (162, 11, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (172, 8),
    (5:19) move the triggering player to (162, 11, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (174, 8),
    (5:19) move the triggering player to (162, 11, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (176, 8),
    (5:19) move the triggering player to (162, 11, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (178, 8),
    (5:19) move the triggering player to (162, 11, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (106, 9),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (108, 9),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (110, 9),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (111, 9),
    (5:19) move the triggering player to (116, 20, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (117, 9),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (119, 9),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (106, 10),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (108, 10),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (110, 10),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (111, 10),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (112, 10),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (113, 10),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (114, 10),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (115, 10),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (116, 10),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (117, 10),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (119, 10),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (168, 10),
    (5:19) move the triggering player to (162, 11, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (170, 10),
    (5:19) move the triggering player to (162, 11, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (172, 10),
    (5:19) move the triggering player to (162, 11, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (176, 10),
    (5:19) move the triggering player to (162, 11, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (178, 10),
    (5:19) move the triggering player to (162, 11, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 11),
    (5:19) move the triggering player to (12, 26, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (14, 11),
    (5:19) move the triggering player to (12, 26, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (15, 11),
    (5:19) move the triggering player to (12, 26, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (108, 11),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (119, 11),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (106, 12),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (107, 12),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (108, 12),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (109, 12),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (110, 12),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (111, 12),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (112, 12),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (113, 12),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (114, 12),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (115, 12),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (116, 12),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (117, 12),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (118, 12),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (119, 12),
    (5:19) move the triggering player to (104, 7, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (168, 12),
    (5:19) move the triggering player to (162, 11, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (170, 12),
    (5:19) move the triggering player to (162, 11, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (172, 12),
    (5:19) move the triggering player to (162, 11, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (174, 12),
    (5:19) move the triggering player to (162, 11, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (178, 12),
    (5:19) move the triggering player to (162, 11, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (76, 14),
    (5:19) move the triggering player to (78, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (168, 14),
    (5:19) move the triggering player to (162, 11, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (170, 14),
    (5:19) move the triggering player to (162, 11, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (172, 14),
    (5:19) move the triggering player to (162, 11, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (174, 14),
    (5:19) move the triggering player to (162, 11, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (176, 14),
    (5:19) move the triggering player to (162, 11, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (9, 15),
    (5:19) move the triggering player to (12, 26, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (10, 15),
    (5:19) move the triggering player to (12, 26, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (11, 15),
    (5:19) move the triggering player to (12, 26, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (76, 15),
    (5:19) move the triggering player to (78, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 16),
    (5:19) move the triggering player to (12, 26, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (76, 16),
    (5:19) move the triggering player to (78, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (126, 16),
    (5:19) move the triggering player to (134, 25, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (133, 16),
    (5:19) move the triggering player to (139, 29, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (142, 16),
    (5:19) move the triggering player to (131, 17, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (168, 16),
    (5:19) move the triggering player to (162, 11, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (172, 16),
    (5:19) move the triggering player to (162, 11, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (174, 16),
    (5:19) move the triggering player to (162, 11, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (176, 16),
    (5:19) move the triggering player to (162, 11, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (178, 16),
    (5:19) move the triggering player to (162, 11, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 17),
    (5:19) move the triggering player to (12, 26, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (76, 17),
    (5:19) move the triggering player to (78, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (126, 17),
    (5:19) move the triggering player to (134, 25, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (133, 17),
    (5:19) move the triggering player to (139, 29, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (142, 17),
    (5:19) move the triggering player to (131, 17, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 18),
    (5:19) move the triggering player to (12, 26, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (77, 18),
    (5:19) move the triggering player to (78, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (78, 18),
    (5:19) move the triggering player to (78, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (79, 18),
    (5:19) move the triggering player to (78, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (80, 18),
    (5:19) move the triggering player to (78, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (126, 18),
    (5:19) move the triggering player to (134, 25, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (133, 18),
    (5:19) move the triggering player to (139, 29, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (142, 18),
    (5:19) move the triggering player to (131, 17, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (130, 20),
    (5:19) move the triggering player to (139, 29, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (136, 20),
    (5:19) move the triggering player to (141, 17, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (29, 21),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (33, 21),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (130, 21),
    (5:19) move the triggering player to (139, 29, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (136, 21),
    (5:19) move the triggering player to (141, 17, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (29, 22),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (33, 22),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (130, 22),
    (5:19) move the triggering player to (139, 29, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (136, 22),
    (5:19) move the triggering player to (141, 17, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 23),
    (5:19) move the triggering player to (12, 26, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (14, 23),
    (5:19) move the triggering player to (12, 26, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (15, 23),
    (5:19) move the triggering player to (12, 26, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (29, 23),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (33, 23),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (72, 23),
    (5:19) move the triggering player to (78, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (73, 23),
    (5:19) move the triggering player to (78, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (74, 23),
    (5:19) move the triggering player to (78, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (75, 23),
    (5:19) move the triggering player to (78, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (22, 24),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (23, 24),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (24, 24),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (34, 24),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (35, 24),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (36, 24),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (76, 24),
    (5:19) move the triggering player to (78, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (126, 24),
    (5:19) move the triggering player to (141, 25, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (135, 24),
    (5:19) move the triggering player to (129, 21, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (142, 24),
    (5:19) move the triggering player to (145, 29, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (29, 25),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (76, 25),
    (5:19) move the triggering player to (78, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (126, 25),
    (5:19) move the triggering player to (141, 25, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (135, 25),
    (5:19) move the triggering player to (129, 21, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (142, 25),
    (5:19) move the triggering player to (145, 29, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (166, 25),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (168, 25),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (170, 25),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (172, 25),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (174, 25),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (176, 25),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (29, 26),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (76, 26),
    (5:19) move the triggering player to (78, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (126, 26),
    (5:19) move the triggering player to (141, 25, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (135, 26),
    (5:19) move the triggering player to (129, 21, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (142, 26),
    (5:19) move the triggering player to (145, 29, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (29, 27),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (76, 27),
    (5:19) move the triggering player to (78, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (166, 27),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (168, 27),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (170, 27),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (172, 27),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (174, 27),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (178, 27),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (30, 28),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (31, 28),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (32, 28),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (34, 28),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (35, 28),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (36, 28),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (67, 28),
    (5:19) move the triggering player to (78, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (68, 28),
    (5:19) move the triggering player to (78, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (69, 28),
    (5:19) move the triggering player to (78, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (70, 28),
    (5:19) move the triggering player to (78, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (76, 28),
    (5:19) move the triggering player to (78, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (77, 28),
    (5:19) move the triggering player to (78, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (78, 28),
    (5:19) move the triggering player to (78, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (79, 28),
    (5:19) move the triggering player to (78, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (80, 28),
    (5:19) move the triggering player to (78, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (140, 28),
    (5:19) move the triggering player to (145, 29, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (146, 28),
    (5:19) move the triggering player to (141, 17, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (25, 29),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (37, 29),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (76, 29),
    (5:19) move the triggering player to (78, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (106, 29),
    (5:19) move the triggering player to (107, 21, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (107, 29),
    (5:19) move the triggering player to (107, 21, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (108, 29),
    (5:19) move the triggering player to (107, 21, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (109, 29),
    (5:19) move the triggering player to (107, 21, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (140, 29),
    (5:19) move the triggering player to (145, 29, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (146, 29),
    (5:19) move the triggering player to (141, 17, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (166, 29),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (168, 29),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (170, 29),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (174, 29),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (176, 29),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (178, 29),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (25, 30),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (37, 30),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (76, 30),
    (5:19) move the triggering player to (78, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (140, 30),
    (5:19) move the triggering player to (145, 29, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (146, 30),
    (5:19) move the triggering player to (141, 17, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (25, 31),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (37, 31),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (76, 31),
    (5:19) move the triggering player to (78, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (140, 31),
    (5:19) move the triggering player to (145, 29, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (146, 31),
    (5:19) move the triggering player to (141, 17, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (166, 31),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (170, 31),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (172, 31),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (174, 31),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (176, 31),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (178, 31),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (22, 32),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (23, 32),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (24, 32),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (26, 32),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (27, 32),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (28, 32),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (30, 32),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (31, 32),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (32, 32),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (76, 32),
    (5:19) move the triggering player to (78, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (29, 33),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (37, 33),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (85, 33),
    (5:19) move the triggering player to (95, 37, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (90, 33),
    (5:19) move the triggering player to (95, 33, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (95, 33),
    (5:19) move the triggering player to (95, 35, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (166, 33),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (168, 33),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (170, 33),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (172, 33),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (174, 33),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (176, 33),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (29, 34),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (37, 34),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (71, 34),
    (5:19) move the triggering player to (78, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (139, 34),
    (5:19) move the triggering player to (146, 35, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (142, 34),
    (5:19) move the triggering player to (122, 46, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (146, 34),
    (5:19) move the triggering player to (137, 35, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (151, 34),
    (5:19) move the triggering player to (155, 35, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (155, 34),
    (5:19) move the triggering player to (156, 25, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (29, 35),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (37, 35),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (71, 35),
    (5:19) move the triggering player to (78, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (85, 35),
    (5:19) move the triggering player to (90, 35, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (90, 35),
    (5:19) move the triggering player to (83, 79, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (95, 35),
    (5:19) move the triggering player to (90, 37, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (110, 35),
    (5:19) move the triggering player to (107, 21, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (132, 35),
    (5:19) move the triggering player to (155, 35, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (138, 35),
    (5:19) move the triggering player to (138, 38, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (140, 35),
    (5:19) move the triggering player to (155, 35, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (145, 35),
    (5:19) move the triggering player to (148, 38, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (147, 35),
    (5:19) move the triggering player to (155, 35, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (150, 35),
    (5:19) move the triggering player to (137, 35, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (152, 35),
    (5:19) move the triggering player to (153, 38, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (154, 35),
    (5:19) move the triggering player to (138, 38, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (156, 35),
    (5:19) move the triggering player to (155, 35, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (166, 35),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (168, 35),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (170, 35),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (172, 35),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (176, 35),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (178, 35),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (34, 36),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (35, 36),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (36, 36),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (71, 36),
    (5:19) move the triggering player to (78, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (110, 36),
    (5:19) move the triggering player to (107, 21, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (131, 36),
    (5:19) move the triggering player to (127, 36, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (133, 36),
    (5:19) move the triggering player to (138, 38, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (139, 36),
    (5:19) move the triggering player to (158, 38, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (143, 36),
    (5:19) move the triggering player to (139, 35, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (146, 36),
    (5:19) move the triggering player to (158, 38, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (151, 36),
    (5:19) move the triggering player to (158, 38, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (155, 36),
    (5:19) move the triggering player to (127, 36, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (25, 37),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (33, 37),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (71, 37),
    (5:19) move the triggering player to (78, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (85, 37),
    (5:19) move the triggering player to (90, 39, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (90, 37),
    (5:19) move the triggering player to (95, 39, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (95, 37),
    (5:19) move the triggering player to (85, 39, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (110, 37),
    (5:19) move the triggering player to (107, 21, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (132, 37),
    (5:19) move the triggering player to (158, 38, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (138, 37),
    (5:19) move the triggering player to (138, 38, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (142, 37),
    (5:19) move the triggering player to (155, 35, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (144, 37),
    (5:19) move the triggering player to (145, 29, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (148, 37),
    (5:19) move the triggering player to (158, 38, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (153, 37),
    (5:19) move the triggering player to (137, 35, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (158, 37),
    (5:19) move the triggering player to (155, 35, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (168, 37),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (170, 37),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (172, 37),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (174, 37),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (176, 37),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (178, 37),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (25, 38),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (33, 38),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (71, 38),
    (5:19) move the triggering player to (78, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (110, 38),
    (5:19) move the triggering player to (107, 21, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (137, 38),
    (5:19) move the triggering player to (158, 38, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (139, 38),
    (5:19) move the triggering player to (155, 35, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (143, 38),
    (5:19) move the triggering player to (158, 38, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (147, 38),
    (5:19) move the triggering player to (137, 35, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (149, 38),
    (5:19) move the triggering player to (155, 35, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (152, 38),
    (5:19) move the triggering player to (159, 34, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (154, 38),
    (5:19) move the triggering player to (158, 38, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (157, 38),
    (5:19) move the triggering player to (156, 25, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (159, 38),
    (5:19) move the triggering player to (127, 36, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (25, 39),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (33, 39),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (67, 39),
    (5:19) move the triggering player to (78, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (68, 39),
    (5:19) move the triggering player to (78, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (69, 39),
    (5:19) move the triggering player to (78, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (70, 39),
    (5:19) move the triggering player to (78, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (72, 39),
    (5:19) move the triggering player to (78, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (73, 39),
    (5:19) move the triggering player to (78, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (74, 39),
    (5:19) move the triggering player to (78, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (75, 39),
    (5:19) move the triggering player to (78, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (85, 39),
    (5:19) move the triggering player to (85, 33, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (90, 39),
    (5:19) move the triggering player to (85, 37, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (95, 39),
    (5:19) move the triggering player to (90, 33, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (101, 39),
    (5:19) move the triggering player to (107, 21, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (102, 39),
    (5:19) move the triggering player to (107, 21, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (103, 39),
    (5:19) move the triggering player to (107, 21, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (104, 39),
    (5:19) move the triggering player to (107, 21, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (138, 39),
    (5:19) move the triggering player to (143, 37, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (148, 39),
    (5:19) move the triggering player to (151, 35, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (153, 39),
    (5:19) move the triggering player to (155, 35, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (158, 39),
    (5:19) move the triggering player to (138, 38, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (166, 39),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (170, 39),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (172, 39),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (174, 39),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (176, 39),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (178, 39),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (26, 40),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (27, 40),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (28, 40),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (30, 40),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (31, 40),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (32, 40),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (38, 40),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (39, 40),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (40, 40),
    (5:19) move the triggering player to (1, 1, 1).

(0:1) Whenever someone moves,
 (1:35) and they move into position (115, 40),
    (5:19) move the triggering player to (107, 21, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (120, 40),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (115, 41),
    (5:19) move the triggering player to (107, 21, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (120, 41),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (166, 41),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (170, 41),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (172, 41),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (174, 41),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (176, 41),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (178, 41),
    (5:19) move the triggering player to (173, 22, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (115, 42),
    (5:19) move the triggering player to (107, 21, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (120, 42),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (45, 43),
    (5:19) move the triggering player to (42, 47, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (115, 43),
    (5:19) move the triggering player to (107, 21, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (120, 43),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (43, 44),
    (5:19) move the triggering player to (46, 45, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (48, 44),
    (5:19) move the triggering player to (44, 57, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (122, 44),
    (5:19) move the triggering player to (133, 48, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (141, 44),
    (5:19) move the triggering player to (133, 48, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (46, 45),
    (5:19) move the triggering player to (43, 49, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (54, 45),
    (5:19) move the triggering player to (68, 46, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (61, 45),
    (5:19) move the triggering player to (47, 48, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (196, 45),
    (5:19) move the triggering player to (197, 53, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (58, 46),
    (5:19) move the triggering player to (68, 46, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (128, 46),
    (5:19) move the triggering player to (144, 48, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (42, 47),
    (5:19) move the triggering player to (42, 47, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (45, 47),
    (5:19) move the triggering player to (53, 47, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (24, 48),
    (5:19) move the triggering player to (37, 66, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (28, 48),
    (5:19) move the triggering player to (37, 66, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (141, 48),
    (5:19) move the triggering player to (133, 48, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (43, 49),
    (5:19) move the triggering player to (48, 44, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (56, 49),
    (5:19) move the triggering player to (68, 46, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (101, 49),
    (5:19) move the triggering player to (107, 21, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (102, 49),
    (5:19) move the triggering player to (107, 21, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (103, 49),
    (5:19) move the triggering player to (107, 21, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (104, 49),
    (5:19) move the triggering player to (107, 21, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (111, 49),
    (5:19) move the triggering player to (107, 21, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (112, 49),
    (5:19) move the triggering player to (107, 21, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (113, 49),
    (5:19) move the triggering player to (107, 21, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (114, 49),
    (5:19) move the triggering player to (107, 21, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (35, 50),
    (5:19) move the triggering player to (37, 66, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (45, 50),
    (5:19) move the triggering player to (42, 47, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (48, 50),
    (5:19) move the triggering player to (45, 47, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (165, 51),
    (5:19) move the triggering player to (183, 62, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (141, 52),
    (5:19) move the triggering player to (133, 48, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (127, 54),
    (5:19) move the triggering player to (133, 48, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (130, 54),
    (5:19) move the triggering player to (133, 48, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (133, 54),
    (5:19) move the triggering player to (133, 48, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (137, 54),
    (5:19) move the triggering player to (133, 48, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (139, 54),
    (5:19) move the triggering player to (133, 48, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (101, 55),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (102, 55),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (103, 55),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (104, 55),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (105, 55),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (106, 55),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (107, 55),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (108, 55),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (109, 55),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (110, 55),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (111, 55),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (112, 55),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (113, 55),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (114, 55),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (115, 55),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (116, 55),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (117, 55),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (101, 56),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (117, 56),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (51, 57),
    (5:19) move the triggering player to (84, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (101, 57),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (103, 57),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (104, 57),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (105, 57),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (106, 57),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (107, 57),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (108, 57),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (109, 57),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (110, 57),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (111, 57),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (112, 57),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (113, 57),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (114, 57),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (115, 57),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (117, 57),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (51, 58),
    (5:19) move the triggering player to (84, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (101, 58),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (103, 58),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (115, 58),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (117, 58),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (126, 58),
    (5:19) move the triggering player to (139, 59, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (130, 58),
    (5:19) move the triggering player to (139, 49, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (51, 59),
    (5:19) move the triggering player to (84, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (69, 59),
    (5:19) move the triggering player to (67, 69, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (70, 59),
    (5:19) move the triggering player to (67, 69, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (84, 59),
    (5:19) move the triggering player to (92, 77, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (101, 59),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (103, 59),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (105, 59),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (106, 59),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (107, 59),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (108, 59),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (109, 59),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (110, 59),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (111, 59),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (112, 59),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (113, 59),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (115, 59),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (117, 59),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (126, 59),
    (5:19) move the triggering player to (139, 59, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (51, 60),
    (5:19) move the triggering player to (84, 5, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (63, 60),
    (5:19) move the triggering player to (67, 69, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (64, 60),
    (5:19) move the triggering player to (67, 69, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (75, 60),
    (5:19) move the triggering player to (67, 60, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (76, 60),
    (5:19) move the triggering player to (67, 60, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (87, 60),
    (5:19) move the triggering player to (92, 77, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (89, 60),
    (5:19) move the triggering player to (92, 77, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (92, 60),
    (5:19) move the triggering player to (92, 77, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (97, 60),
    (5:19) move the triggering player to (92, 77, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (101, 60),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (103, 60),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (105, 60),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (113, 60),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (115, 60),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (117, 60),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (176, 60),
    (5:19) move the triggering player to (174, 53, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (180, 60),
    (5:19) move the triggering player to (183, 62, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (232, 60),
    (5:19) move the triggering player to (223, 59, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (57, 61),
    (5:19) move the triggering player to (58, 73, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (58, 61),
    (5:19) move the triggering player to (58, 73, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (85, 61),
    (5:19) move the triggering player to (92, 77, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (88, 61),
    (5:19) move the triggering player to (92, 77, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (101, 61),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (103, 61),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (105, 61),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (107, 61),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (108, 61),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (109, 61),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (110, 61),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (111, 61),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (113, 61),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (115, 61),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (117, 61),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (126, 61),
    (5:19) move the triggering player to (139, 59, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (130, 61),
    (5:19) move the triggering player to (123, 77, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (135, 61),
    (5:19) move the triggering player to (139, 59, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (93, 62),
    (5:19) move the triggering player to (92, 77, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (101, 62),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (103, 62),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (105, 62),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (107, 62),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (111, 62),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (113, 62),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (115, 62),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (117, 62),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (126, 62),
    (5:19) move the triggering player to (139, 59, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (130, 62),
    (5:19) move the triggering player to (123, 77, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (138, 62),
    (5:19) move the triggering player to (140, 93, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (140, 62),
    (5:19) move the triggering player to (140, 93, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (178, 62),
    (5:19) move the triggering player to (183, 62, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (84, 63),
    (5:19) move the triggering player to (92, 77, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (90, 63),
    (5:19) move the triggering player to (92, 77, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (101, 63),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (103, 63),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (105, 63),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (107, 63),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (109, 63),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (111, 63),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (113, 63),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (115, 63),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (117, 63),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (88, 64),
    (5:19) move the triggering player to (92, 77, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (96, 64),
    (5:19) move the triggering player to (92, 77, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (101, 64),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (103, 64),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (105, 64),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (107, 64),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (109, 64),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (111, 64),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (113, 64),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (115, 64),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (117, 64),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (141, 64),
    (5:19) move the triggering player to (140, 93, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (176, 64),
    (5:19) move the triggering player to (183, 62, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (180, 64),
    (5:19) move the triggering player to (183, 62, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (66, 65),
    (5:19) move the triggering player to (58, 63, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (67, 65),
    (5:19) move the triggering player to (58, 63, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (101, 65),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (103, 65),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (105, 65),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (107, 65),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (109, 65),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (111, 65),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (113, 65),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (115, 65),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (117, 65),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (126, 65),
    (5:19) move the triggering player to (139, 59, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (130, 65),
    (5:19) move the triggering player to (139, 59, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (135, 65),
    (5:19) move the triggering player to (139, 59, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (138, 65),
    (5:19) move the triggering player to (140, 93, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (72, 66),
    (5:19) move the triggering player to (61, 72, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (73, 66),
    (5:19) move the triggering player to (61, 72, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (85, 66),
    (5:19) move the triggering player to (92, 77, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (87, 66),
    (5:19) move the triggering player to (92, 77, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (101, 66),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (103, 66),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (105, 66),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (107, 66),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (109, 66),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (110, 66),
    (5:19) move the triggering player to (123, 8, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (111, 66),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (113, 66),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (115, 66),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (117, 66),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (126, 66),
    (5:19) move the triggering player to (139, 59, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (130, 66),
    (5:19) move the triggering player to (139, 59, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (140, 66),
    (5:19) move the triggering player to (140, 93, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (63, 67),
    (5:19) move the triggering player to (73, 70, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (64, 67),
    (5:19) move the triggering player to (73, 70, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (89, 67),
    (5:19) move the triggering player to (92, 77, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (96, 67),
    (5:19) move the triggering player to (92, 77, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (101, 67),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (103, 67),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (105, 67),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (107, 67),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (109, 67),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (110, 67),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (111, 67),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (113, 67),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (115, 67),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (117, 67),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (6, 68),
    (5:19) move the triggering player to (9, 65, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (7, 68),
    (5:19) move the triggering player to (9, 65, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (8, 68),
    (5:19) move the triggering player to (9, 65, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (9, 68),
    (5:19) move the triggering player to (9, 65, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (10, 68),
    (5:19) move the triggering player to (9, 65, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (35, 68),
    (5:19) move the triggering player to (37, 66, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (69, 68),
    (5:19) move the triggering player to (64, 70, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (70, 68),
    (5:19) move the triggering player to (64, 70, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (101, 68),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (103, 68),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (105, 68),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (107, 68),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (113, 68),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (115, 68),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (117, 68),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (139, 68),
    (5:19) move the triggering player to (140, 93, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (180, 68),
    (5:19) move the triggering player to (174, 72, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (184, 68),
    (5:19) move the triggering player to (174, 72, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (189, 68),
    (5:19) move the triggering player to (174, 72, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (57, 69),
    (5:19) move the triggering player to (64, 62, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (58, 69),
    (5:19) move the triggering player to (64, 62, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (60, 69),
    (5:19) move the triggering player to (76, 63, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (61, 69),
    (5:19) move the triggering player to (76, 63, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (75, 69),
    (5:19) move the triggering player to (80, 73, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (76, 69),
    (5:19) move the triggering player to (80, 73, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (101, 69),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (103, 69),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (105, 69),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (107, 69),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (108, 69),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (109, 69),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (110, 69),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (111, 69),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (112, 69),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (113, 69),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (115, 69),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (117, 69),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (126, 69),
    (5:19) move the triggering player to (139, 59, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (130, 69),
    (5:19) move the triggering player to (139, 59, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (135, 69),
    (5:19) move the triggering player to (139, 59, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (26, 70),
    (5:19) move the triggering player to (104, 6, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (101, 70),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (103, 70),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (105, 70),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (115, 70),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (117, 70),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (126, 70),
    (5:19) move the triggering player to (139, 59, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (130, 70),
    (5:19) move the triggering player to (139, 59, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (138, 70),
    (5:19) move the triggering player to (140, 93, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (141, 70),
    (5:19) move the triggering player to (140, 93, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (189, 70),
    (5:19) move the triggering player to (174, 72, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (35, 71),
    (5:19) move the triggering player to (37, 66, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (101, 71),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (103, 71),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (105, 71),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (106, 71),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (107, 71),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (108, 71),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (109, 71),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (110, 71),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (111, 71),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (112, 71),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (113, 71),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (114, 71),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (115, 71),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (117, 71),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (83, 72),
    (5:19) move the triggering player to (83, 79, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (85, 72),
    (5:19) move the triggering player to (83, 79, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (101, 72),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (103, 72),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (117, 72),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (180, 72),
    (5:19) move the triggering player to (174, 72, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (184, 72),
    (5:19) move the triggering player to (174, 72, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (189, 72),
    (5:19) move the triggering player to (174, 72, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (66, 73),
    (5:19) move the triggering player to (73, 62, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (67, 73),
    (5:19) move the triggering player to (73, 62, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (82, 73),
    (5:19) move the triggering player to (83, 79, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (84, 73),
    (5:19) move the triggering player to (83, 77, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (86, 73),
    (5:19) move the triggering player to (82, 74, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (101, 73),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (103, 73),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (104, 73),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (105, 73),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (106, 73),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (107, 73),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (108, 73),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (109, 73),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (110, 73),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (111, 73),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (112, 73),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (113, 73),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (114, 73),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (115, 73),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (116, 73),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (117, 73),
    (5:19) move the triggering player to (118, 51, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (139, 73),
    (5:19) move the triggering player to (140, 93, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (232, 73),
    (5:19) move the triggering player to (235, 71, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (234, 73),
    (5:19) move the triggering player to (235, 71, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (236, 73),
    (5:19) move the triggering player to (235, 71, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (238, 73),
    (5:19) move the triggering player to (235, 71, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (35, 74),
    (5:19) move the triggering player to (37, 66, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (83, 74),
    (5:19) move the triggering player to (83, 79, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (85, 74),
    (5:19) move the triggering player to (83, 79, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (140, 74),
    (5:19) move the triggering player to (140, 93, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (142, 74),
    (5:19) move the triggering player to (140, 93, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (169, 74),
    (5:19) move the triggering player to (201, 3, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (180, 74),
    (5:19) move the triggering player to (174, 72, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (184, 74),
    (5:19) move the triggering player to (174, 72, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (189, 74),
    (5:19) move the triggering player to (191, 69, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (191, 74),
    (5:19) move the triggering player to (174, 72, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (8, 75),
    (5:19) move the triggering player to (9, 71, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (9, 75),
    (5:19) move the triggering player to (9, 71, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (10, 75),
    (5:19) move the triggering player to (9, 71, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (11, 75),
    (5:19) move the triggering player to (9, 71, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (72, 75),
    (5:19) move the triggering player to (70, 62, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (73, 75),
    (5:19) move the triggering player to (70, 62, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (82, 75),
    (5:19) move the triggering player to (85, 75, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (84, 75),
    (5:19) move the triggering player to (83, 79, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (86, 75),
    (5:19) move the triggering player to (82, 78, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (232, 75),
    (5:19) move the triggering player to (235, 71, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (234, 75),
    (5:19) move the triggering player to (235, 71, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (236, 75),
    (5:19) move the triggering player to (235, 71, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (238, 75),
    (5:19) move the triggering player to (235, 71, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (35, 76),
    (5:19) move the triggering player to (37, 66, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (83, 76),
    (5:19) move the triggering player to (83, 79, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (85, 76),
    (5:19) move the triggering player to (83, 79, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (139, 76),
    (5:19) move the triggering player to (140, 93, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (141, 76),
    (5:19) move the triggering player to (140, 93, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (180, 76),
    (5:19) move the triggering player to (174, 72, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (184, 76),
    (5:19) move the triggering player to (174, 72, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (189, 76),
    (5:19) move the triggering player to (174, 72, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (82, 77),
    (5:19) move the triggering player to (92, 77, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (84, 77),
    (5:19) move the triggering player to (87, 79, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (86, 77),
    (5:19) move the triggering player to (83, 79, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (140, 77),
    (5:19) move the triggering player to (140, 93, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (232, 77),
    (5:19) move the triggering player to (225, 80, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (234, 77),
    (5:19) move the triggering player to (235, 71, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (236, 77),
    (5:19) move the triggering player to (235, 71, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (238, 77),
    (5:19) move the triggering player to (235, 71, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (83, 78),
    (5:19) move the triggering player to (83, 79, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (85, 78),
    (5:19) move the triggering player to (86, 74, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (138, 78),
    (5:19) move the triggering player to (140, 93, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (82, 79),
    (5:19) move the triggering player to (83, 79, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (84, 79),
    (5:19) move the triggering player to (83, 79, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (86, 79),
    (5:19) move the triggering player to (83, 79, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (232, 79),
    (5:19) move the triggering player to (235, 71, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (234, 79),
    (5:19) move the triggering player to (235, 71, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (236, 79),
    (5:19) move the triggering player to (235, 71, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (238, 79),
    (5:19) move the triggering player to (235, 71, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (8, 80),
    (5:19) move the triggering player to (19, 3, 139).

(0:1) Whenever someone moves,
 (1:35) and they move into position (9, 80),
    (5:19) move the triggering player to (20, 3, 139).

(0:1) Whenever someone moves,
 (1:35) and they move into position (10, 80),
    (5:19) move the triggering player to (21, 3, 139).

(0:1) Whenever someone moves,
 (1:35) and they move into position (83, 80),
    (5:19) move the triggering player to (86, 72, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (85, 80),
    (5:19) move the triggering player to (83, 79, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (87, 80),
    (5:19) move the triggering player to (86, 78, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (140, 80),
    (5:19) move the triggering player to (140, 93, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (180, 80),
    (5:19) move the triggering player to (190, 100, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (182, 80),
    (5:19) move the triggering player to (190, 100, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (183, 80),
    (5:19) move the triggering player to (190, 100, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (185, 80),
    (5:19) move the triggering player to (190, 100, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (9, 81),
    (5:19) move the triggering player to (20, 3, 139).

(0:1) Whenever someone moves,
 (1:35) and they move into position (139, 81),
    (5:19) move the triggering player to (140, 93, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (183, 81),
    (5:19) move the triggering player to (190, 100, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 82),
    (5:19) move the triggering player to (4, 79, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (53, 82),
    (5:19) move the triggering player to (47, 83, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (55, 82),
    (5:19) move the triggering player to (47, 83, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (57, 82),
    (5:19) move the triggering player to (47, 83, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (59, 82),
    (5:19) move the triggering player to (47, 83, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (178, 82),
    (5:19) move the triggering player to (187, 71, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (141, 83),
    (5:19) move the triggering player to (140, 93, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (142, 83),
    (5:19) move the triggering player to (140, 93, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (53, 84),
    (5:19) move the triggering player to (47, 83, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (55, 84),
    (5:19) move the triggering player to (47, 83, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (57, 84),
    (5:19) move the triggering player to (46, 97, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (59, 84),
    (5:19) move the triggering player to (47, 83, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (127, 84),
    (5:19) move the triggering player to (128, 84, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (129, 84),
    (5:19) move the triggering player to (128, 84, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (140, 84),
    (5:19) move the triggering player to (140, 93, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (178, 84),
    (5:19) move the triggering player to (187, 71, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (186, 84),
    (5:19) move the triggering player to (187, 71, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (195, 84),
    (5:19) move the triggering player to (197, 73, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (197, 84),
    (5:19) move the triggering player to (197, 73, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (199, 84),
    (5:19) move the triggering player to (197, 73, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (127, 85),
    (5:19) move the triggering player to (128, 84, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (129, 85),
    (5:19) move the triggering player to (128, 84, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (174, 85),
    (5:19) move the triggering player to (114, 96, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (53, 86),
    (5:19) move the triggering player to (47, 83, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (55, 86),
    (5:19) move the triggering player to (47, 83, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (57, 86),
    (5:19) move the triggering player to (47, 83, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (59, 86),
    (5:19) move the triggering player to (47, 83, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (122, 86),
    (5:19) move the triggering player to (128, 84, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (123, 86),
    (5:19) move the triggering player to (128, 84, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (124, 86),
    (5:19) move the triggering player to (128, 84, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (125, 86),
    (5:19) move the triggering player to (128, 84, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (127, 86),
    (5:19) move the triggering player to (128, 84, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (129, 86),
    (5:19) move the triggering player to (128, 84, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (138, 86),
    (5:19) move the triggering player to (140, 93, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (178, 86),
    (5:19) move the triggering player to (187, 71, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (186, 86),
    (5:19) move the triggering player to (187, 71, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (208, 86),
    (5:19) move the triggering player to (202, 92, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (212, 86),
    (5:19) move the triggering player to (202, 92, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (216, 86),
    (5:19) move the triggering player to (202, 92, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (122, 87),
    (5:19) move the triggering player to (128, 84, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (123, 87),
    (5:19) move the triggering player to (133, 86, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (124, 87),
    (5:19) move the triggering player to (128, 84, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (125, 87),
    (5:19) move the triggering player to (128, 84, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (127, 87),
    (5:19) move the triggering player to (128, 84, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (129, 87),
    (5:19) move the triggering player to (128, 84, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (140, 87),
    (5:19) move the triggering player to (140, 93, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (142, 87),
    (5:19) move the triggering player to (140, 93, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (53, 88),
    (5:19) move the triggering player to (47, 83, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (55, 88),
    (5:19) move the triggering player to (47, 83, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (57, 88),
    (5:19) move the triggering player to (47, 83, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (59, 88),
    (5:19) move the triggering player to (47, 83, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (122, 88),
    (5:19) move the triggering player to (128, 84, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (127, 88),
    (5:19) move the triggering player to (128, 84, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (129, 88),
    (5:19) move the triggering player to (128, 84, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (178, 88),
    (5:19) move the triggering player to (187, 71, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (182, 88),
    (5:19) move the triggering player to (190, 100, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (186, 88),
    (5:19) move the triggering player to (187, 71, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (214, 88),
    (5:19) move the triggering player to (202, 92, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (218, 88),
    (5:19) move the triggering player to (202, 92, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (122, 89),
    (5:19) move the triggering player to (128, 84, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (123, 89),
    (5:19) move the triggering player to (128, 84, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (124, 89),
    (5:19) move the triggering player to (128, 84, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (125, 89),
    (5:19) move the triggering player to (128, 84, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (126, 89),
    (5:19) move the triggering player to (128, 84, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (127, 89),
    (5:19) move the triggering player to (128, 84, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (129, 89),
    (5:19) move the triggering player to (128, 84, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (139, 89),
    (5:19) move the triggering player to (140, 93, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (181, 89),
    (5:19) move the triggering player to (190, 100, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (182, 89),
    (5:19) move the triggering player to (183, 96, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (183, 89),
    (5:19) move the triggering player to (190, 100, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (193, 89),
    (5:19) move the triggering player to (197, 73, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (195, 89),
    (5:19) move the triggering player to (197, 73, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (197, 89),
    (5:19) move the triggering player to (197, 73, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (26, 90),
    (5:19) move the triggering player to (24, 93, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (129, 90),
    (5:19) move the triggering player to (128, 84, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (178, 90),
    (5:19) move the triggering player to (187, 71, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (208, 90),
    (5:19) move the triggering player to (202, 92, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (212, 90),
    (5:19) move the triggering player to (202, 92, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (121, 91),
    (5:19) move the triggering player to (128, 84, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (122, 91),
    (5:19) move the triggering player to (128, 84, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (123, 91),
    (5:19) move the triggering player to (128, 84, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (124, 91),
    (5:19) move the triggering player to (128, 84, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (125, 91),
    (5:19) move the triggering player to (128, 84, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (126, 91),
    (5:19) move the triggering player to (128, 84, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (127, 91),
    (5:19) move the triggering player to (128, 84, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (128, 91),
    (5:19) move the triggering player to (128, 84, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (129, 91),
    (5:19) move the triggering player to (128, 84, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (26, 92),
    (5:19) move the triggering player to (24, 93, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (222, 92),
    (5:19) move the triggering player to (202, 92, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (26, 93),
    (5:19) move the triggering player to (24, 93, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (26, 94),
    (5:19) move the triggering player to (24, 93, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (122, 94),
    (5:19) move the triggering player to (133, 87, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (193, 94),
    (5:19) move the triggering player to (197, 73, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (197, 94),
    (5:19) move the triggering player to (197, 73, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (199, 94),
    (5:19) move the triggering player to (197, 73, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (212, 94),
    (5:19) move the triggering player to (202, 92, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (216, 94),
    (5:19) move the triggering player to (202, 92, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (220, 94),
    (5:19) move the triggering player to (202, 92, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (225, 94),
    (5:19) move the triggering player to (202, 92, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (26, 95),
    (5:19) move the triggering player to (24, 93, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (120, 95),
    (5:19) move the triggering player to (162, 11, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (139, 95),
    (5:19) move the triggering player to (140, 93, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (120, 96),
    (5:19) move the triggering player to (162, 11, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (218, 96),
    (5:19) move the triggering player to (202, 92, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (222, 96),
    (5:19) move the triggering player to (202, 92, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (26, 97),
    (5:19) move the triggering player to (24, 93, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (120, 97),
    (5:19) move the triggering player to (162, 11, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (120, 98),
    (5:19) move the triggering player to (162, 11, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (139, 98),
    (5:19) move the triggering player to (140, 93, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (161, 98),
    (5:19) move the triggering player to (168, 86, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (208, 98),
    (5:19) move the triggering player to (202, 92, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (216, 98),
    (5:19) move the triggering player to (202, 92, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (218, 98),
    (5:19) move the triggering player to (174, 73, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (141, 99),
    (5:19) move the triggering player to (140, 93, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (178, 99),
    (5:19) move the triggering player to (168, 96, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (193, 99),
    (5:19) move the triggering player to (197, 73, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (195, 99),
    (5:19) move the triggering player to (197, 73, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (197, 99),
    (5:19) move the triggering player to (190, 99, 47).

(0:1) Whenever someone moves,
 (1:35) and they move into position (199, 99),
    (5:19) move the triggering player to (197, 73, 47).

\* NPC Spawns */
(0:0) When everything is starting up,

