*/ 5 - Aeven
*
*\

\* Warps */

(0:1) Whenever someone moves,
 (1:35) and they move into position (3, 0),
    (5:19) move the triggering player to (11, 95, 65).

(0:1) Whenever someone moves,
 (1:35) and they move into position (4, 0),
    (5:19) move the triggering player to (12, 95, 65).

(0:1) Whenever someone moves,
 (1:35) and they move into position (5, 0),
    (5:19) move the triggering player to (13, 95, 65).

(0:1) Whenever someone moves,
 (1:35) and they move into position (33, 0),
    (5:19) move the triggering player to (19, 47, 4).

(0:1) Whenever someone moves,
 (1:35) and they move into position (34, 0),
    (5:19) move the triggering player to (20, 47, 4).

(0:1) Whenever someone moves,
 (1:35) and they move into position (40, 0),
    (5:19) move the triggering player to (26, 47, 4).

(0:1) Whenever someone moves,
 (1:35) and they move into position (41, 0),
    (5:19) move the triggering player to (27, 47, 4).

(0:1) Whenever someone moves,
 (1:35) and they move into position (42, 0),
    (5:19) move the triggering player to (28, 47, 4).

(0:1) Whenever someone moves,
 (1:35) and they move into position (51, 0),
    (5:19) move the triggering player to (34, 47, 4).

(0:1) Whenever someone moves,
 (1:35) and they move into position (52, 0),
    (5:19) move the triggering player to (35, 47, 4).

(0:1) Whenever someone moves,
 (1:35) and they move into position (81, 0),
    (5:19) move the triggering player to (22, 24, 103).

(0:1) Whenever someone moves,
 (1:35) and they move into position (82, 0),
    (5:19) move the triggering player to (24, 24, 103).

(0:1) Whenever someone moves,
 (1:35) and they move into position (83, 0),
    (5:19) move the triggering player to (25, 24, 103).

(0:1) Whenever someone moves,
 (1:35) and they move into position (7, 1),
    (5:19) move the triggering player to (1, 1, 18).

(0:1) Whenever someone moves,
 (1:35) and they move into position (85, 3),
    (5:19) move the triggering player to (89, 1, 18).

(0:1) Whenever someone moves,
 (1:35) and they move into position (36, 10),
    (5:19) move the triggering player to (35, 13, 76).

(0:1) Whenever someone moves,
 (1:35) and they move into position (19, 13),
    (5:19) move the triggering player to (13, 7, 91).

(0:1) Whenever someone moves,
 (1:35) and they move into position (36, 16),
    (5:19) move the triggering player to (18, 9, 90).

(0:1) Whenever someone moves,
 (1:35) and they move into position (28, 17),
    (5:19) move the triggering player to (2, 19, 90).

(0:1) Whenever someone moves,
 (1:35) and they move into position (19, 22),
    (5:19) move the triggering player to (13, 7, 92).

(0:1) Whenever someone moves,
 (1:35) and they move into position (63, 23),
    (5:19) move the triggering player to (15, 8, 51).

(0:1) Whenever someone moves,
 (1:35) and they move into position (36, 25),
    (5:19) move the triggering player to (19, 13, 84).

(0:1) Whenever someone moves,
 (1:35) and they move into position (28, 26),
    (5:19) move the triggering player to (2, 12, 84).

(0:1) Whenever someone moves,
 (1:35) and they move into position (19, 31),
    (5:19) move the triggering player to (13, 7, 93).

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 32),
    (5:19) move the triggering player to (2, 2, 108).

(0:1) Whenever someone moves,
 (1:35) and they move into position (36, 35),
    (5:19) move the triggering player to (17, 8, 15).

(0:1) Whenever someone moves,
 (1:35) and they move into position (19, 40),
    (5:19) move the triggering player to (18, 8, 108).

(0:1) Whenever someone moves,
 (1:35) and they move into position (86, 45),
    (5:19) move the triggering player to (1, 21, 7).

(0:1) Whenever someone moves,
 (1:35) and they move into position (86, 46),
    (5:19) move the triggering player to (1, 22, 7).

(0:1) Whenever someone moves,
 (1:35) and they move into position (86, 47),
    (5:19) move the triggering player to (1, 23, 7).

(0:1) Whenever someone moves,
 (1:35) and they move into position (86, 48),
    (5:19) move the triggering player to (1, 24, 7).

(0:1) Whenever someone moves,
 (1:35) and they move into position (86, 49),
    (5:19) move the triggering player to (1, 25, 7).

(0:1) Whenever someone moves,
 (1:35) and they move into position (36, 56),
    (5:19) move the triggering player to (18, 7, 14).

(0:1) Whenever someone moves,
 (1:35) and they move into position (11, 57),
    (5:19) move the triggering player to (5, 13, 156).

(0:1) Whenever someone moves,
 (1:35) and they move into position (18, 57),
    (5:19) move the triggering player to (5, 13, 157).

(0:1) Whenever someone moves,
 (1:35) and they move into position (25, 57),
    (5:19) move the triggering player to (36, 11, 154).

(0:1) Whenever someone moves,
 (1:35) and they move into position (73, 57),
    (5:19) move the triggering player to (13, 7, 94).

(0:1) Whenever someone moves,
 (1:35) and they move into position (54, 61),
    (5:19) move the triggering player to (17, 7, 106).

(0:1) Whenever someone moves,
 (1:35) and they move into position (54, 69),
    (5:19) move the triggering player to (15, 7, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (11, 72),
    (5:19) move the triggering player to (5, 13, 27).

(0:1) Whenever someone moves,
 (1:35) and they move into position (18, 72),
    (5:19) move the triggering player to (5, 13, 26).

(0:1) Whenever someone moves,
 (1:35) and they move into position (25, 72),
    (5:19) move the triggering player to (5, 13, 25).

(0:1) Whenever someone moves,
 (1:35) and they move into position (32, 72),
    (5:19) move the triggering player to (5, 13, 24).

(0:1) Whenever someone moves,
 (1:35) and they move into position (51, 73),
    (5:19) move the triggering player to (7, 15, 50).

(0:1) Whenever someone moves,
 (1:35) and they move into position (7, 74),
    (5:19) move the triggering player to (1, 89, 18).

(0:1) Whenever someone moves,
 (1:35) and they move into position (67, 74),
    (5:19) move the triggering player to (5, 11, 283).

(0:1) Whenever someone moves,
 (1:35) and they move into position (72, 74),
    (5:19) move the triggering player to (5, 11, 89).

(0:1) Whenever someone moves,
 (1:35) and they move into position (85, 74),
    (5:19) move the triggering player to (89, 89, 18).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 78),
    (5:19) move the triggering player to (38, 15, 186).

(0:1) Whenever someone moves,
 (1:35) and they move into position (86, 78),
    (5:19) move the triggering player to (1, 18, 16).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 79),
    (5:19) move the triggering player to (38, 16, 186).

(0:1) Whenever someone moves,
 (1:35) and they move into position (86, 79),
    (5:19) move the triggering player to (1, 19, 16).

(0:1) Whenever someone moves,
 (1:35) and they move into position (0, 80),
    (5:19) move the triggering player to (38, 17, 186).

(0:1) Whenever someone moves,
 (1:35) and they move into position (86, 80),
    (5:19) move the triggering player to (1, 20, 16).

(0:1) Whenever someone moves,
 (1:35) and they move into position (40, 86),
    (5:19) move the triggering player to (14, 1, 2).

(0:1) Whenever someone moves,
 (1:35) and they move into position (41, 86),
    (5:19) move the triggering player to (15, 1, 2).

(0:1) Whenever someone moves,
 (1:35) and they move into position (42, 86),
    (5:19) move the triggering player to (16, 1, 2).

\* Doors */

(0:151) When someone tries to open a door at (19, 13),
 (1:80) and they can see position (19, 13),
    (5:200) open the door at (19, 13) on the map.

(0:151) When someone tries to open a door at (36, 16),
 (1:80) and they can see position (36, 16),
    (5:200) open the door at (36, 16) on the map.

(0:151) When someone tries to open a door at (19, 22),
 (1:80) and they can see position (19, 22),
    (5:200) open the door at (19, 22) on the map.

(0:151) When someone tries to open a door at (63, 23),
 (1:80) and they can see position (63, 23),
    (5:200) open the door at (63, 23) on the map.

(0:151) When someone tries to open a door at (36, 25),
 (1:80) and they can see position (36, 25),
    (5:200) open the door at (36, 25) on the map.

(0:151) When someone tries to open a door at (19, 31),
 (1:80) and they can see position (19, 31),
    (5:200) open the door at (19, 31) on the map.

(0:151) When someone tries to open a door at (36, 35),
 (1:80) and they can see position (36, 35),
    (5:200) open the door at (36, 35) on the map.

(0:151) When someone tries to open a door at (19, 40),
 (1:80) and they can see position (19, 40),
    (5:200) open the door at (19, 40) on the map.

(0:151) When someone tries to open a door at (36, 56),
 (1:80) and they can see position (36, 56),
    (5:200) open the door at (36, 56) on the map.

(0:151) When someone tries to open a door at (11, 57),
 (1:80) and they can see position (11, 57),
    (5:200) open the door at (11, 57) on the map.

(0:151) When someone tries to open a door at (18, 57),
 (1:80) and they can see position (18, 57),
    (5:200) open the door at (18, 57) on the map.

(0:151) When someone tries to open a door at (25, 57),
 (1:80) and they can see position (25, 57),
    (5:200) open the door at (25, 57) on the map.

(0:151) When someone tries to open a door at (73, 57),
 (1:80) and they can see position (73, 57),
    (5:200) open the door at (73, 57) on the map.

(0:151) When someone tries to open a door at (54, 61),
 (1:80) and they can see position (54, 61),
    (5:200) open the door at (54, 61) on the map.

(0:151) When someone tries to open a door at (54, 69),
 (1:80) and they can see position (54, 69),
    (5:200) open the door at (54, 69) on the map.

(0:151) When someone tries to open a door at (11, 72),
 (1:80) and they can see position (11, 72),
    (5:200) open the door at (11, 72) on the map.

(0:151) When someone tries to open a door at (18, 72),
 (1:80) and they can see position (18, 72),
    (5:200) open the door at (18, 72) on the map.

(0:151) When someone tries to open a door at (25, 72),
 (1:80) and they can see position (25, 72),
    (5:200) open the door at (25, 72) on the map.

(0:151) When someone tries to open a door at (32, 72),
 (1:80) and they can see position (32, 72),
    (5:200) open the door at (32, 72) on the map.

(0:151) When someone tries to open a door at (51, 73),
 (1:80) and they can see position (51, 73),
    (5:200) open the door at (51, 73) on the map.

(0:151) When someone tries to open a door at (67, 74),
 (1:80) and they can see position (67, 74),
    (5:200) open the door at (67, 74) on the map.

(0:151) When someone tries to open a door at (72, 74),
 (1:80) and they can see position (72, 74),
    (5:200) open the door at (72, 74) on the map.

\* NPC Spawns */
(0:0) When everything is starting up,
    (5:220) spawn a new NPC 1 at (5, 40) on the map.
    (5:220) spawn a new NPC 1 at (79, 40) on the map.
    (5:220) spawn a new NPC 2 at (46, 40) on the map.
    (5:220) spawn a new NPC 1 at (46, 40) on the map.
    (5:220) spawn a new NPC 53 at (41, 47) on the map.
    (5:220) spawn a new NPC 54 at (41, 47) on the map.
    (5:220) spawn a new NPC 55 at (41, 47) on the map.
    (5:220) spawn a new NPC 75 at (41, 47) on the map.
    (5:220) spawn a new NPC 76 at (41, 47) on the map.
    (5:220) spawn a new NPC 1 at (41, 47) on the map.
    (5:220) spawn a new NPC 278 at (80, 1) on the map.
    (5:220) spawn a new NPC 275 at (85, 43) on the map.
    (5:220) spawn a new NPC 275 at (85, 51) on the map.
    (5:220) spawn a new NPC 277 at (85, 76) on the map.
    (5:220) spawn a new NPC 276 at (1, 76) on the map.
    (5:220) spawn a new NPC 276 at (1, 82) on the map.
    (5:220) spawn a new NPC 278 at (84, 1) on the map.
    (5:220) spawn a new NPC 280 at (44, 83) on the map.
    (5:220) spawn a new NPC 1 at (6, 3) on the map.
    (5:220) spawn a new NPC 1 at (82, 5) on the map.
    (5:220) spawn a new NPC 1 at (82, 80) on the map.
    (5:220) spawn a new NPC 1 at (5, 80) on the map.
    (5:220) spawn a new NPC 1 at (25, 47) on the map.
    (5:220) spawn a new NPC 1 at (60, 47) on the map.
    (5:220) spawn a new NPC 1 at (41, 65) on the map.
    (5:220) spawn a new NPC 1 at (41, 26) on the map.

