*/ 54 - Ancient entrance
*
*\

\* Warps */

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 0),
    (5:19) move the triggering player to (15, 32, 55).

(0:1) Whenever someone moves,
 (1:35) and they move into position (13, 0),
    (5:19) move the triggering player to (16, 32, 55).

(0:1) Whenever someone moves,
 (1:35) and they move into position (14, 0),
    (5:19) move the triggering player to (17, 32, 55).

\* NPC Spawns */
(0:0) When everything is starting up,

