*/ 56 - No name specified
*
*\

\* Warps */

(0:1) Whenever someone moves,
 (1:35) and they move into position (9, 12),
    (5:19) move the triggering player to (48, 24, 34).

(0:1) Whenever someone moves,
 (1:35) and they move into position (10, 12),
    (5:19) move the triggering player to (48, 24, 34).

\* NPC Spawns */
(0:0) When everything is starting up,
    (5:220) spawn a new NPC 37 at (6, 5) on the map.

