*/ 58 - No name specified
*
*\

\* Warps */

(0:1) Whenever someone moves,
 (1:35) and they move into position (14, 7),
    (5:19) move the triggering player to (12, 12, 34).

(0:1) Whenever someone moves,
 (1:35) and they move into position (14, 8),
    (5:19) move the triggering player to (12, 12, 34).

\* NPC Spawns */
(0:0) When everything is starting up,
    (5:220) spawn a new NPC 303 at (9, 9) on the map.

