*/ 72 - Sky House
*
*\

\* Warps */

(0:1) Whenever someone moves,
 (1:35) and they move into position (5, 9),
    (5:19) move the triggering player to (19, 20, 71).

(0:1) Whenever someone moves,
 (1:35) and they move into position (6, 9),
    (5:19) move the triggering player to (19, 20, 71).

\* NPC Spawns */
(0:0) When everything is starting up,
    (5:220) spawn a new NPC 192 at (4, 5) on the map.

