*/ 79 - Crypt
*
*\

\* Warps */

(0:1) Whenever someone moves,
 (1:35) and they move into position (11, 2),
    (5:19) move the triggering player to (10, 3, 62).

\* NPC Spawns */
(0:0) When everything is starting up,
    (5:220) spawn a new NPC 4 at (5, 6) on the map.
    (5:220) spawn a new NPC 4 at (15, 5) on the map.
    (5:220) spawn a new NPC 4 at (18, 19) on the map.
    (5:220) spawn a new NPC 4 at (6, 18) on the map.

