*/ 96 - No name specified
*
*\

\* Warps */

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 7),
    (5:19) move the triggering player to (38, 38, 29).

(0:1) Whenever someone moves,
 (1:35) and they move into position (12, 8),
    (5:19) move the triggering player to (38, 38, 29).

\* NPC Spawns */
(0:0) When everything is starting up,
    (5:220) spawn a new NPC 39 at (7, 7) on the map.

