*/ 97 - No name specified
*
*\

\* Warps */

(0:1) Whenever someone moves,
 (1:35) and they move into position (8, 16),
    (5:19) move the triggering player to (23, 18, 29).

(0:1) Whenever someone moves,
 (1:35) and they move into position (9, 16),
    (5:19) move the triggering player to (23, 18, 29).

\* NPC Spawns */
(0:0) When everything is starting up,
    (5:220) spawn a new NPC 16 at (1, 13) on the map.

