*/ 98 - No name specified
*
*\

\* Warps */

(0:1) Whenever someone moves,
 (1:35) and they move into position (5, 12),
    (5:19) move the triggering player to (13, 21, 29).

(0:1) Whenever someone moves,
 (1:35) and they move into position (6, 12),
    (5:19) move the triggering player to (13, 21, 29).

\* NPC Spawns */
(0:0) When everything is starting up,
    (5:220) spawn a new NPC 41 at (5, 3) on the map.
    (5:220) spawn a new NPC 40 at (5, 2) on the map.

