*/ 99 - No name specified
*
*\

\* Warps */

(0:1) Whenever someone moves,
 (1:35) and they move into position (5, 12),
    (5:19) move the triggering player to (19, 18, 16).

(0:1) Whenever someone moves,
 (1:35) and they move into position (6, 12),
    (5:19) move the triggering player to (19, 18, 16).

\* NPC Spawns */
(0:0) When everything is starting up,
    (5:220) spawn a new NPC 42 at (4, 1) on the map.

